"""Emit the option A circuits that consume POPT v2 (docs/pop-transcript-v2.md). circom 2.2.3, --prime secq256r1.

  $PY gen_popt2.py phone <sr> [--nf]     # circuits/main/oa2t_s48.circom (sr 48000) / oa2t_s44 (44100) [+ _nf]
  $PY gen_popt2.py pair                  # circuits/main/oa2t_pair.circom

Per-phone statement (role R = roleB ? B : A, circuit compiled for ONE sample rate SR):
  (1) The 311-byte POPT v2 transcript is rebuilt byte for byte and ECDSA-P-256-signed (sha256) by the hidden
      device key; the key has an SBcred3 credential from the public issuer, unexpired at validAt; the signed
      sample_rate == SR; the signed delta == DELTA; own X != partner X.
      Derived exactly from signed fields: p_self = a_self - self_os_delta, a_partner = a_self + half (A) /
      a_self - half (B). play_frame_position, play_nano_time, rec_frame0_nano_time, commit_hash, pubs,
      rec_root, a_self, p_partner, half stay private.
  (2)-(5) as the optionA-v2 statement (gen_circuit.py): int16 samples opened under the signed rec_root
      (4-ary Poseidon7 tree, depth 4 here), self window [p_self - delta, p_self + delta] with a_self the first
      lag >= 9 %, partner lag a_partner >= 9 % inside [p_partner - WPRE, p_partner + WPOST].
  (6) output halfCommit = Poseidon7(TAG_HALF2; nonceHi, nonceLo, attempt, roleB, sr, half, salt, X_self,
      X_partner). Hiding (salt), so it names nobody; the pair proof opens both and checks the keys cross.
  --nf: also output nullifier = Poseidon7(TAG_NULL; holder_secret, nonce) bound to the credential's holder
      commitment. Only for the "none" proof-of-human adapter (docs/pop-human-adapters.md): with World ID / ENS
      the adapter nullifiers do this job outside the circuit.
  No pairTag: the session link is the public nonce; the pair tag is computed by the verifier from the two
  adapter nullifiers (verifier/popzk.py).

Pair statement (oa2t_pair): public nonceHi, nonceLo, attempt, commitA, commitB, srA, srB. Opens commitA (roleB 0)
and commitB (roleB 1) with private halves, salts and X_A, X_B (crossed: A's partner is B's self and vice
versa), X_A != X_B, halves are i32, rates in [36000, 96000], and NEAR with both rates by cross-multiplying:
  -20 < c/2 (hA/srA - hB/srB) < 60   <=>   c N > -40 S  and  c N < 120 S,  N = hA srB - hB srA, S = srA srB
exactly server/pop/verdict.decide() (flight <= -20 impossible, >= 60 too_far).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from gen_circuit import LIB, TAG_HOLD, TAG_NULL  # noqa: E402  (before oa_rate, which puts optionA-jbl250 on sys.path)
import oa_rate as R  # noqa: E402

HERE = Path(__file__).resolve().parent
CIRC = HERE / "circuits"
DEPTH = 4
TAG_HALF2 = 8
TAG_FS2 = 9
C_CM_S, IMPOSSIBLE_CM, NEAR_CM, SR_MIN, SR_MAX = 34300, -20, 60, 36000, 96000   # server/pop/constants.py

LIB_POPT = """
// ---- POPT v2 additions: Merkle path of a given depth (4-ary), leaf index 2*D bits.
template MerklePathD(D) {
    signal input leaf;
    signal input idx;
    signal input ch[D][4];
    signal output root;
    component ib = Num2Bits(2 * D);
    ib.in <== idx;
    component nd[D];
    signal s3[D];
    signal t1[D];
    signal t2[D];
    signal t3[D];
    var cur = leaf;
    for (var l = 0; l < D; l++) {
        var b0 = ib.out[2 * l];
        var b1 = ib.out[2 * l + 1];
        s3[l] <== b0 * b1;
        t1[l] <== b0 * (ch[l][1] - ch[l][0]);
        t2[l] <== b1 * (ch[l][2] - ch[l][0]);
        t3[l] <== s3[l] * (ch[l][3] - ch[l][2] - ch[l][1] + ch[l][0]);
        cur === ch[l][0] + t1[l] + t2[l] + t3[l];
        nd[l] = Node5();
        for (var k = 0; k < 4; k++) { nd[l].c[k] <== ch[l][k]; }
        cur = nd[l].out;
    }
    root <== cur;
}

template OpenLeavesD(NL, D) {
    signal input x[NL][1024];
    signal input first;
    signal input ch[NL][D][4];
    signal input root;
    component lf[NL];
    component mp[NL];
    for (var i = 0; i < NL; i++) {
        lf[i] = Leaf1024();
        lf[i].x <== x[i];
        mp[i] = MerklePathD(D);
        mp[i].leaf <== lf[i].h;
        mp[i].idx <== first + i;
        mp[i].ch <== ch[i];
        mp[i].root === root;
    }
}
"""


def emit_lib():
    (CIRC / "oa2tlib.circom").write_text(LIB + LIB_POPT)


def emit_phone(sr: int, nf: bool):
    p, g = R.params(sr), R.geometry(sr)
    L, HM, M, B, DELTA, WPRE, WPOST = p["L"], p["HM"], p["M"], p["B"], p["DELTA"], p["WPRE"], p["WPOST"]
    K, NS, NLS, NP, NLP = g["K"], g["NS"], g["NLS"], g["NP"], g["NLP"]
    W = R.width_W(sr)
    h = p["h"]
    name = f"oa2t_s{sr // 1000}" + ("_nf" if nf else "")
    nfs = 12 + 2 * K
    TL = 311
    src = f"""pragma circom 2.2.3;
// generated by gen_popt2.py: POPT v2 per-phone, SR={sr} L={L} DELTA={DELTA} K={K} NS={NS} NLS={NLS} NP={NP} NLP={NLP}
// WPRE={WPRE} WPOST={WPOST} M={M} HM={HM} B={B} W={W} DEPTH={DEPTH} nullifier={nf}
include "oa2tlib.circom";
include "sb.circom";

template OA2T() {{
    var SR = {sr};
    var L = {L};
    var K = {K};
    var DELTA = {DELTA};
    var HM = {HM};
    var M = {M};
    var NS = {NS};
    var NP = {NP};
    var NLS = {NLS};
    var NLP = {NLP};
    var WPRE = {WPRE};
    var WPOST = {WPOST};
    var B = {B};
    var h[M] = [{", ".join(str(v) for v in h)}];

    // ---------------- public
    signal input nonceHi;
    signal input nonceLo;
    signal input attempt;
    signal input roleB;
    signal input codeHi;          // code_commit as 2 x 128-bit limbs (verifier recomputes from the templates)
    signal input codeLo;
    signal input cIs[L];          // own template, int8, derived by the verifier from the revealed code seed
    signal input cQs[L];
    signal input cIp[L];          // partner template
    signal input cQp[L];
    signal input issuerX;
    signal input issuerY;
    signal input sr;              // the signed sample_rate; must equal SR (this circuit is compiled per rate)
    signal input validAt;
    signal output halfCommit;
{"    signal output nullifier;" if nf else ""}
    // ---------------- private: POPT v2 fields, signature, credential
    signal input ownPub[64];      // X||Y (the SEC1 0x04 prefix is a constant in the transcript)
    signal input partnerPub[64];
    signal input halfBytes[4];
    signal input recBytes[32];    // rec_root
    signal input pfpB[8];         // play_frame_position
    signal input pntB[8];         // play_nano_time
    signal input rf0B[8];         // rec_frame0_nano_time
    signal input sodB[4];         // self_os_delta
    signal input chB[32];         // commit_hash
    signal input aSelfB[4];
    signal input pPartnerB[4];
    signal input deltaB[2];
    signal input sig_r;
    signal input sig_sInv;
    signal input exp[8];
    signal input cred_r;
    signal input cred_sInv;
    signal input holdCommit[32];
{"    signal input holderSecret;" if nf else ""}
    signal input salt;
    // ---------------- private: recording openings, claimed self curve, arrival selector
    signal input xs[NLS][1024];
    signal input chS[NLS][{DEPTH}][4];
    signal input leafS;
    signal input xp[NLP][1024];
    signal input chP[NLP][{DEPTH}][4];
    signal input leafP;
    signal input I[K];
    signal input Q[K];
    signal input u[K];

    // ================= (1) POPT v2 transcript, signature, credential
    component hdr = PublicHeader();
    hdr.nonceHi <== nonceHi;
    hdr.nonceLo <== nonceLo;
    hdr.attempt <== attempt;
    hdr.sr <== sr;
    hdr.validAt <== validAt;
    sr === SR;
    roleB * (roleB - 1) === 0;
    component bO = BytesBits(64); bO.in <== ownPub;
    component bP = BytesBits(64); bP.in <== partnerPub;
    component bH = BytesBits(4); bH.in <== halfBytes;
    component bR = BytesBits(32); bR.in <== recBytes;
    component bF = BytesBits(8); bF.in <== pfpB;
    component bN = BytesBits(8); bN.in <== pntB;
    component bZ = BytesBits(8); bZ.in <== rf0B;
    component bS = BytesBits(4); bS.in <== sodB;
    component bC = BytesBits(32); bC.in <== chB;
    component bAS = BytesBits(4); bAS.in <== aSelfB;
    component bPP = BytesBits(4); bPP.in <== pPartnerB;
    component bD = BytesBits(2); bD.in <== deltaB;
    component cH = NumBitsBE(128); cH.in <== codeHi;
    component cL = NumBitsBE(128); cL.in <== codeLo;
    component sha = Sha256(8 * {TL});
    var k = 0;
    var magic[5] = [0x50, 0x4F, 0x50, 0x54, 0x02];   // "POPT", version 2
    for (var i = 0; i < 5; i++) {{ for (var j = 0; j < 8; j++) {{ sha.in[k] <== (magic[i] >> (7 - j)) & 1; k++; }} }}
    for (var j = 0; j < 6; j++) {{ sha.in[k] <== (0x41 >> (7 - j)) & 1; k++; }}   // role 0x41 / 0x42
    sha.in[k] <== roleB; k++;
    sha.in[k] <== 1 - roleB; k++;
    for (var i = 0; i < 8; i++) {{ sha.in[k] <== hdr.attemptBits[i]; k++; }}
    for (var i = 0; i < 256; i++) {{ sha.in[k] <== hdr.nonceBits[i]; k++; }}
    for (var j = 0; j < 8; j++) {{ sha.in[k] <== (0x04 >> (7 - j)) & 1; k++; }}
    for (var i = 0; i < 512; i++) {{ sha.in[k] <== bO.out[i]; k++; }}
    for (var j = 0; j < 8; j++) {{ sha.in[k] <== (0x04 >> (7 - j)) & 1; k++; }}
    for (var i = 0; i < 512; i++) {{ sha.in[k] <== bP.out[i]; k++; }}
    for (var i = 0; i < 32; i++) {{ sha.in[k] <== hdr.srBits[i]; k++; }}
    for (var i = 0; i < 32; i++) {{ sha.in[k] <== bH.out[i]; k++; }}
    for (var i = 0; i < 256; i++) {{ sha.in[k] <== bR.out[i]; k++; }}
    for (var i = 0; i < 64; i++) {{ sha.in[k] <== bF.out[i]; k++; }}
    for (var i = 0; i < 64; i++) {{ sha.in[k] <== bN.out[i]; k++; }}
    for (var i = 0; i < 64; i++) {{ sha.in[k] <== bZ.out[i]; k++; }}
    for (var i = 0; i < 32; i++) {{ sha.in[k] <== bS.out[i]; k++; }}
    for (var i = 0; i < 256; i++) {{ sha.in[k] <== bC.out[i]; k++; }}
    for (var i = 0; i < 32; i++) {{ sha.in[k] <== bAS.out[i]; k++; }}
    for (var i = 0; i < 32; i++) {{ sha.in[k] <== bPP.out[i]; k++; }}
    for (var i = 0; i < 16; i++) {{ sha.in[k] <== bD.out[i]; k++; }}
    for (var i = 0; i < 128; i++) {{ sha.in[k] <== cH.out[i]; k++; }}
    for (var i = 0; i < 128; i++) {{ sha.in[k] <== cL.out[i]; k++; }}

    component xO = PackBytes(32); component yO = PackBytes(32); component xP = PackBytes(32);
    for (var i = 0; i < 32; i++) {{ xO.in[i] <== ownPub[i]; yO.in[i] <== ownPub[32 + i]; xP.in[i] <== partnerPub[i]; }}
    component dsig = VerifyDigestSig();
    dsig.digest <== sha.out;
    dsig.r <== sig_r;
    dsig.sInv <== sig_sInv;
    dsig.pubX <== xO.out;
    dsig.pubY <== yO.out;

    // credential SBcred3 = "SBcred3" | X||Y | expiry u64 | holder_commit(32), SHA-256 + ECDSA by the issuer
    component bE = BytesBits(8); bE.in <== exp;
    component bHC = BytesBits(32); bHC.in <== holdCommit;
    component csha = Sha256(8 * 111);
    var kc = 0;
    var cmag[7] = [0x53, 0x42, 0x63, 0x72, 0x65, 0x64, 0x33];
    for (var i = 0; i < 7; i++) {{ for (var j = 0; j < 8; j++) {{ csha.in[kc] <== (cmag[i] >> (7 - j)) & 1; kc++; }} }}
    for (var i = 0; i < 512; i++) {{ csha.in[kc] <== bO.out[i]; kc++; }}
    for (var i = 0; i < 64; i++) {{ csha.in[kc] <== bE.out[i]; kc++; }}
    for (var i = 0; i < 256; i++) {{ csha.in[kc] <== bHC.out[i]; kc++; }}
    component isig = VerifyDigestSig();
    isig.digest <== csha.out;
    isig.r <== cred_r;
    isig.sInv <== cred_sInv;
    isig.pubX <== issuerX;
    isig.pubY <== issuerY;
    component expV = PackBytes(8); expV.in <== exp;
    component notExpired = LessEqThan(64);
    notExpired.in[0] <== validAt;
    notExpired.in[1] <== expV.out;
    notExpired.out === 1;
    component same = IsEqual(); same.in[0] <== xO.out; same.in[1] <== xP.out; same.out === 0;
"""
    if nf:
        src += f"""    component hc = Sponge16(1, {TAG_HOLD}); hc.in[0] <== holderSecret;
    component hcv = PackBytes(32); hcv.in <== holdCommit;
    hcv.out === hc.o1;
    component nfh = Sponge16(3, {TAG_NULL});
    nfh.in[0] <== holderSecret; nfh.in[1] <== nonceHi; nfh.in[2] <== nonceLo;
    nullifier <== nfh.o1;
"""
    src += f"""
    // signed values; p_self and a_partner are exact functions of signed fields
    component vR = PackBytes(32); vR.in <== recBytes;
    component vAS = PackBytes(4); vAS.in <== aSelfB;
    component vPP = PackBytes(4); vPP.in <== pPartnerB;
    component vD = PackBytes(2); vD.in <== deltaB;
    component vH = SignedI32(); vH.bits <== bH.out;
    component vS = SignedI32(); vS.bits <== bS.out;
    vD.out === DELTA;
    signal recRoot <== vR.out;
    signal aSelf <== vAS.out;
    signal pPartner <== vPP.out;
    signal half <== vH.out;
    signal pSelf <== aSelf - vS.out;
    signal sgnHalf <== (1 - 2 * roleB) * half;
    signal aPartner <== aSelf + sgnHalf;

    // ================= (2) open the recording (tree depth {DEPTH})
    signal oS <== pSelf - DELTA - HM - 1024 * leafS;
    component oSb = Num2Bits(10); oSb.in <== oS;
    component opS = OpenLeavesD(NLS, {DEPTH});
    opS.x <== xs; opS.first <== leafS; opS.ch <== chS; opS.root <== recRoot;
    signal oP <== aPartner - HM - 1024 * leafP;
    component oPb = Num2Bits(10); oPb.in <== oP;
    component opP = OpenLeavesD(NLP, {DEPTH});
    opP.x <== xp; opP.first <== leafP; opP.ch <== chP; opP.root <== recRoot;
    component shS = Barrel1024(NLS * 1024, NS);
    for (var i = 0; i < NLS; i++) {{ for (var j = 0; j < 1024; j++) {{ shS.in[1024 * i + j] <== xs[i][j]; }} }}
    shS.bits <== oSb.out;
    component shP = Barrel1024(NLP * 1024, NP);
    for (var i = 0; i < NLP; i++) {{ for (var j = 0; j < 1024; j++) {{ shP.in[1024 * i + j] <== xp[i][j]; }} }}
    shP.bits <== oPb.out;

    // ================= (3) Fiat-Shamir + Freivalds on the self curve
    component fs = Sponge16({nfs}, {TAG_FS2 + (nfs << 8)});
    fs.in[0] <== nonceHi; fs.in[1] <== nonceLo; fs.in[2] <== attempt; fs.in[3] <== roleB;
    fs.in[4] <== recRoot; fs.in[5] <== pSelf; fs.in[6] <== pPartner; fs.in[7] <== DELTA;
    fs.in[8] <== aSelf; fs.in[9] <== aPartner; fs.in[10] <== codeHi; fs.in[11] <== codeLo;
    for (var j = 0; j < K; j++) {{ fs.in[12 + j] <== I[j]; fs.in[12 + K + j] <== Q[j]; }}
    signal r <== fs.o1;
    signal rho <== fs.o2;
    var N = K + L - 1;
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) {{ pw[i] <== pw[i - 1] * r; }}
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) {{ S[m] <== S[m - 1] + pw[m - 1] * shS.out[HM + m - 1]; }}
    signal v[L];
    signal uu[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {{
        v[n] <== rho * cQs[n];
        uu[n] <== (cIs[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + uu[n] * (S[n + K] - S[n]);
    }}
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var j = 0; j < K; j++) {{
        li[j + 1] <== li[j] + pw[j] * I[j];
        lq[j + 1] <== lq[j] + pw[j] * Q[j];
    }}
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];

    signal EY[N + 1];
    EY[0] <== 0;
    for (var m = 0; m < N; m++) {{
        var yl = 0;
        for (var t = 0; t < M; t++) {{ if (h[t] != 0) {{ yl += h[t] * shS.out[m + t]; }} }}
        EY[m + 1] <== EY[m] + yl * yl;
    }}
    signal cna[L + 1];
    cna[0] <== 0;
    for (var n = 0; n < L; n++) {{ cna[n + 1] <== cna[n] + cIs[n] * cIs[n]; }}

    // ================= (4) self arrival: first lag >= bar in [p_self - delta, p_self + delta]
    u[K - 1] === 0;
    var usum = 0;
    for (var j = 0; j < K; j++) {{
        u[j] * (u[j] - 1) === 0;
        if (j > 0) {{ u[j] * (1 - u[j - 1]) === 0; }}
        usum += u[j];
    }}
    usum === aSelf - pSelf + DELTA;
    signal C[K];
    signal i2[K];
    signal env2[K];
    signal pu[K];
    signal pe[K];
    component rk[K];
    for (var j = 0; j < K; j++) {{
        C[j] <== (EY[j + L] - EY[j]) * cna[L];
        i2[j] <== I[j] * I[j];
        env2[j] <== i2[j] + Q[j] * Q[j];
        var D = C[j] - B * env2[j];
        var e = (j == 0 ? 1 : u[j - 1]) - u[j];
        pu[j] <== u[j] * (D - 1);
        pe[j] <== e * D;
        rk[j] = Range({W});
        rk[j].in <== pu[j] - pe[j];
    }}

    // ================= (5) partner arrival
    signal ipI[L + 1];
    signal ipQ[L + 1];
    ipI[0] <== 0;
    ipQ[0] <== 0;
    for (var n = 0; n < L; n++) {{
        ipI[n + 1] <== ipI[n] + cIp[n] * shP.out[HM + n];
        ipQ[n + 1] <== ipQ[n] + cQp[n] * shP.out[HM + n];
    }}
    signal EP[L + 1];
    EP[0] <== 0;
    for (var m = 0; m < L; m++) {{
        var yl = 0;
        for (var t = 0; t < M; t++) {{ if (h[t] != 0) {{ yl += h[t] * shP.out[m + t]; }} }}
        EP[m + 1] <== EP[m] + yl * yl;
    }}
    signal cnp[L + 1];
    cnp[0] <== 0;
    for (var n = 0; n < L; n++) {{ cnp[n + 1] <== cnp[n] + cIp[n] * cIp[n]; }}
    signal pi2 <== ipI[L] * ipI[L];
    signal penv2 <== pi2 + ipQ[L] * ipQ[L];
    signal pC <== EP[L] * cnp[L];
    component rp = Range({W});
    rp.in <== B * penv2 - pC;
    component w0 = Num2Bits(33); w0.in <== aPartner - pPartner + WPRE;
    component w1 = Num2Bits(33); w1.in <== pPartner + WPOST - aPartner;

    // ================= (6) hiding half commitment (sr and both key X's inside; no pair tag)
    component hcm = Sponge16(9, {TAG_HALF2});
    hcm.in[0] <== nonceHi; hcm.in[1] <== nonceLo; hcm.in[2] <== attempt; hcm.in[3] <== roleB;
    hcm.in[4] <== sr; hcm.in[5] <== half; hcm.in[6] <== salt; hcm.in[7] <== xO.out; hcm.in[8] <== xP.out;
    halfCommit <== hcm.o1;
}}

component main {{public [nonceHi, nonceLo, attempt, roleB, codeHi, codeLo, cIs, cQs, cIp, cQp, issuerX, issuerY, sr, validAt]}} = OA2T();
"""
    (CIRC / "main").mkdir(parents=True, exist_ok=True)
    (CIRC / "main" / f"{name}.circom").write_text(src)
    meta = {"name": name, "sr": sr, "nf": nf, "depth": DEPTH, "W": W, **{k: v for k, v in p.items() if k != "h"},
            **g, "fir": h, "public_inputs": ["nonceHi", "nonceLo", "attempt", "roleB", "codeHi", "codeLo", "cIs",
                                             "cQs", "cIp", "cQp", "issuerX", "issuerY", "sr", "validAt"],
            "outputs": ["halfCommit"] + (["nullifier"] if nf else [])}
    (CIRC / "main" / f"{name}.json").write_text(json.dumps(meta, indent=1))
    print(CIRC / "main" / f"{name}.circom")


def emit_pair():
    src = f"""pragma circom 2.2.3;
// generated by gen_popt2.py: pair statement over two POPT v2 per-phone half commitments, per-phone sample rates.
include "oa2tlib.circom";

template Pair2() {{
    signal input nonceHi;
    signal input nonceLo;
    signal input attempt;
    signal input commitA;
    signal input commitB;
    signal input srA;
    signal input srB;
    signal input halfA;
    signal input saltA;
    signal input halfB;
    signal input saltB;
    signal input xA;          // X of device A's key (A's own, B's partner)
    signal input xB;
    component ca = Sponge16(9, {TAG_HALF2});
    ca.in[0] <== nonceHi; ca.in[1] <== nonceLo; ca.in[2] <== attempt; ca.in[3] <== 0;
    ca.in[4] <== srA; ca.in[5] <== halfA; ca.in[6] <== saltA; ca.in[7] <== xA; ca.in[8] <== xB;
    ca.o1 === commitA;
    component cb = Sponge16(9, {TAG_HALF2});
    cb.in[0] <== nonceHi; cb.in[1] <== nonceLo; cb.in[2] <== attempt; cb.in[3] <== 1;
    cb.in[4] <== srB; cb.in[5] <== halfB; cb.in[6] <== saltB; cb.in[7] <== xB; cb.in[8] <== xA;
    cb.o1 === commitB;
    component same = IsEqual(); same.in[0] <== xA; same.in[1] <== xB; same.out === 0;
    // i32 halves, rates in [SR_MIN, SR_MAX]
    component ra = Num2Bits(32); ra.in <== halfA + (1 << 31);
    component rb = Num2Bits(32); rb.in <== halfB + (1 << 31);
    component sa0 = Num2Bits(17); sa0.in <== srA - {SR_MIN};
    component sa1 = Num2Bits(17); sa1.in <== {SR_MAX} - srA;
    component sb0 = Num2Bits(17); sb0.in <== srB - {SR_MIN};
    component sb1 = Num2Bits(17); sb1.in <== {SR_MAX} - srB;
    // NEAR iff {IMPOSSIBLE_CM} < c/2 (hA/srA - hB/srB) < {NEAR_CM}, c = {C_CM_S} cm/s, times 2 srA srB > 0.
    // |c N| < 34300 * 2^31 * 2^17 * 2 < 2^65 and 2 NEAR S < 2^41, so (value - 1) in 70 bits <=> value >= 1.
    signal t1 <== halfA * srB;
    signal t2 <== halfB * srA;
    signal S <== srA * srB;
    signal N <== t1 - t2;
    component gtLo = Num2Bits(70); gtLo.in <== {C_CM_S} * N + {-2 * IMPOSSIBLE_CM} * S - 1;
    component ltHi = Num2Bits(70); ltHi.in <== {2 * NEAR_CM} * S - {C_CM_S} * N - 1;
}}

component main {{public [nonceHi, nonceLo, attempt, commitA, commitB, srA, srB]}} = Pair2();
"""
    (CIRC / "main" / "oa2t_pair.circom").write_text(src)
    print(CIRC / "main" / "oa2t_pair.circom")


if __name__ == "__main__":
    a = sys.argv[1:]
    emit_lib()
    if a[0] == "phone":
        emit_phone(int(a[1]), "--nf" in a)
    elif a[0] == "pair":
        emit_pair()
