// sbzk: compile / prove / verify the sound-bound co-presence statement
// with longfellow-zk (Ligero + sumcheck, Fp256Base, rate 7, 132 queries).
//
//   sbzk compile <circuit.bin>
//   sbzk prove   <circuit.bin> <witness.txt> <proof.bin> [--force]
//   sbzk verify  <circuit.bin> <public.txt>  <proof.bin>
//
// Exit codes: 0 ok, 1 prove refused / verify rejected, 2 usage/io error.
// --force: produce a proof even if the witness does not satisfy the circuit
// (uses the test-only forging prover generated by gen_forge.sh), to
// show that the VERIFIER rejects it, not only the honest prover.
#include <sys/resource.h>

#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#include "algebra/convolution.h"
#include "algebra/fp2.h"
#include "algebra/reed_solomon.h"
#include "arrays/dense.h"
#include "circuits/compiler/circuit_dump.h"
#include "circuits/compiler/compiler.h"
#include "circuits/ecdsa/verify_witness.h"
#include "circuits/logic/bit_plucker_encoder.h"
#include "circuits/logic/compiler_backend.h"
#include "circuits/logic/logic.h"
#include "circuits/sha/flatsha256_witness.h"
#include "ec/p256.h"
#include "proto/circuit_reader.h"
#include "proto/circuit_writer.h"
#include "random/secure_random_engine.h"
#include "random/transcript.h"
#include "sbzk_circuit.h"
#include "sbzk_forge.h"
#include "sumcheck/circuit.h"
#include "util/crypto.h"
#include "util/log.h"
#include "util/readbuffer.h"
#include "zk/zk_proof.h"
#include "zk/zk_prover.h"
#include "zk/zk_verifier.h"

using namespace proofs;
using Field = Fp256Base;
using Elt = Field::Elt;
using FNat = Field::N;
using KV = std::map<std::string, std::vector<uint8_t>>;

static constexpr size_t kRate = 7, kReq = 132;  // mdoc v7 params, ~109-bit
static const char kLabel[] = "sound-bound/SBzk1";

static double now_s() {
  using namespace std::chrono;
  return duration<double>(steady_clock::now().time_since_epoch()).count();
}
static double rss_mb() {
  struct rusage ru;
  getrusage(RUSAGE_SELF, &ru);
  return ru.ru_maxrss / 1048576.0;  // macOS: bytes
}
static std::vector<uint8_t> slurp(const char* p) {
  std::ifstream f(p, std::ios::binary);
  if (!f) { fprintf(stderr, "cannot read %s\n", p); exit(2); }
  return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)), {});
}
static void spit(const char* p, const std::vector<uint8_t>& v) {
  std::ofstream f(p, std::ios::binary);
  f.write((const char*)v.data(), v.size());
}
static KV read_kv(const char* p) {
  KV kv;
  std::ifstream f(p);
  if (!f) { fprintf(stderr, "cannot read %s\n", p); exit(2); }
  std::string k, h;
  while (f >> k >> h) {
    std::vector<uint8_t> b(h.size() / 2);
    for (size_t i = 0; i < b.size(); ++i) b[i] = std::stoi(h.substr(2 * i, 2), nullptr, 16);
    kv[k] = b;
  }
  return kv;
}
static const std::vector<uint8_t>& get(const KV& kv, const std::string& k, size_t n) {
  auto it = kv.find(k);
  if (it == kv.end() || it->second.size() != n) {
    fprintf(stderr, "missing/bad key %s\n", k.c_str());
    exit(2);
  }
  return it->second;
}
static FNat nat_be(const uint8_t* be) {
  uint8_t tmp[FNat::kBytes];
  for (size_t i = 0; i < FNat::kBytes; ++i) tmp[i] = be[FNat::kBytes - 1 - i];
  return FNat::of_bytes(tmp);
}
static std::vector<uint8_t> sha256(const std::vector<uint8_t>& m) {
  std::vector<uint8_t> d(32);
  proofs::SHA256 s;
  s.Update(m.data(), m.size());
  s.DigestData(d.data());
  return d;
}

// ---------------------------------------------------------------- circuit
static std::unique_ptr<Circuit<Field>> make_circuit() {
  using CompilerBackend = CompilerBackend<Field>;
  using LogicCircuit = Logic<Field, CompilerBackend>;
  using SB = sbzk::SoundBound<LogicCircuit, Field, P256>;
  QuadCircuit<Field> Q(p256_base);
  const CompilerBackend cbk(&Q);
  const LogicCircuit LC(&cbk, p256_base);
  SB sb(LC, p256, n256_order);
  typename SB::Public pub;
  pub.input(LC);
  Q.private_input();
  typename SB::Witness w;
  w.input(LC);
  sb.assert_statement(pub, w);
  auto C = Q.mkcircuit(/*nc=*/1);
  dump_info("sound-bound SBzk1", Q);
  printf("circuit: depth=%zu wires=%zu inputs=%zu quad_terms=%zu npub_in=%zu nl=%zu\n",
         Q.depth_, Q.nwires_, Q.ninput_, Q.nquad_terms_, (size_t)C->npub_in, (size_t)C->nl);
  return C;
}

// ---------------------------------------------------------------- witness
static void push_bytes(DenseFiller<Field>& f, const uint8_t* b, size_t n) {
  for (size_t i = 0; i < n; ++i) f.push_back(b[i], 8, p256_base);
}
static void push_bytes(DenseFiller<Field>& f, const std::vector<uint8_t>& b) {
  push_bytes(f, b.data(), b.size());
}
static void fill_sha(DenseFiller<Field>& f, const FlatSHA256Witness::BlockWitness& bw) {
  BitPluckerEncoder<Field, 3> E(p256_base);
  for (size_t k = 0; k < 48; ++k) f.push_back(E.mkpacked_v32(bw.outw[k]));
  for (size_t k = 0; k < 64; ++k) {
    f.push_back(E.mkpacked_v32(bw.oute[k]));
    f.push_back(E.mkpacked_v32(bw.outa[k]));
  }
  for (size_t k = 0; k < 8; ++k) f.push_back(E.mkpacked_v32(bw.h1[k]));
}
static void sha_blocks(const std::vector<uint8_t>& m, size_t nb, DenseFiller<Field>& f) {
  std::vector<FlatSHA256Witness::BlockWitness> bw(nb);
  std::vector<uint8_t> in(64 * nb);
  uint8_t numb = 0;
  FlatSHA256Witness::transform_and_witness_message(m.size(), m.data(), nb, numb, in.data(),
                                                   bw.data());
  check(numb == nb, "unexpected sha block count");
  for (auto& b : bw) fill_sha(f, b);
}
static bool ecdsa_fill(DenseFiller<Field>& f, const uint8_t* pk64, const std::vector<uint8_t>& digest,
                       const std::vector<uint8_t>& r, const std::vector<uint8_t>& s) {
  VerifyWitness3<P256, Fp256Scalar> w(p256_scalar, p256);
  Elt px = p256_base.to_montgomery(nat_be(pk64));
  Elt py = p256_base.to_montgomery(nat_be(pk64 + 32));
  bool ok = w.compute_witness(px, py, nat_be(digest.data()), nat_be(r.data()), nat_be(s.data()));
  w.fill_witness(f);
  return ok;
}

// Fill public part (W and pub share the same prefix).
static void fill_public(DenseFiller<Field>& f, const KV& kv) {
  f.push_back(p256_base.one());
  f.push_back(p256_base.to_montgomery(nat_be(get(kv, "issuer_x", 32).data())));
  f.push_back(p256_base.to_montgomery(nat_be(get(kv, "issuer_y", 32).data())));
  push_bytes(f, get(kv, "nonce", 32));
  push_bytes(f, get(kv, "attempt", 1));
  push_bytes(f, get(kv, "now", 8));
  push_bytes(f, get(kv, "nullifier", 32));
}

static void fill_witness(DenseFiller<Field>& f, const KV& kv) {
  fill_public(f, kv);
  const auto& nonce = get(kv, "nonce", 32);
  const auto& attempt = get(kv, "attempt", 1);
  const auto& sr = get(kv, "sr", 4);
  const char* names[2] = {"A", "B"};
  for (int R = 0; R < 2; ++R) {
    std::string p = names[R], o = names[1 - R];
    const auto& dpk = get(kv, p + ".dpk", 64);
    const auto& odpk = get(kv, o + ".dpk", 64);
    const auto& half = get(kv, p + ".half", 4);
    const auto& rec = get(kv, p + ".rec", 32);
    const auto& ts = get(kv, p + ".ts", 8);
    const auto& exp = get(kv, p + ".exp", 8);
    push_bytes(f, dpk);
    push_bytes(f, half);
    push_bytes(f, rec);
    push_bytes(f, ts);
    push_bytes(f, exp);
    std::vector<uint8_t> cred = {'S', 'B', 'c', 'r', 'e', 'd', '1'};
    cred.insert(cred.end(), dpk.begin(), dpk.end());
    cred.insert(cred.end(), exp.begin(), exp.end());
    std::vector<uint8_t> tr = {'S', 'B', 'v', '1'};
    tr.insert(tr.end(), nonce.begin(), nonce.end());
    tr.push_back(attempt[0]);
    tr.push_back(R == 0 ? 0x41 : 0x42);
    tr.insert(tr.end(), dpk.begin(), dpk.end());
    tr.insert(tr.end(), odpk.begin(), odpk.end());
    tr.insert(tr.end(), sr.begin(), sr.end());
    tr.insert(tr.end(), half.begin(), half.end());
    tr.insert(tr.end(), rec.begin(), rec.end());
    tr.push_back(1);
    tr.insert(tr.end(), ts.begin(), ts.end());
    check(tr.size() == sbzk::kTrLen && cred.size() == sbzk::kCredLen, "lengths");
    std::vector<uint8_t> ipk(64);
    memcpy(&ipk[0], get(kv, "issuer_x", 32).data(), 32);
    memcpy(&ipk[32], get(kv, "issuer_y", 32).data(), 32);
    bool ok1 = ecdsa_fill(f, ipk.data(), sha256(cred), get(kv, p + ".cred_r", 32),
                          get(kv, p + ".cred_s", 32));
    bool ok2 = ecdsa_fill(f, dpk.data(), sha256(tr), get(kv, p + ".sig_r", 32),
                          get(kv, p + ".sig_s", 32));
    if (!ok1 || !ok2) fprintf(stderr, "note: ecdsa witness for %s flagged (cred=%d dev=%d)\n", p.c_str(), ok1, ok2);
    sha_blocks(cred, sbzk::kCredBlocks, f);
    sha_blocks(tr, sbzk::kTrBlocks, f);
  }
  push_bytes(f, sr);
  const auto& holder = get(kv, "holder", 32);
  push_bytes(f, holder);
  std::vector<uint8_t> nm(holder);
  nm.insert(nm.end(), nonce.begin(), nonce.end());
  sha_blocks(nm, sbzk::kNullBlocks, f);
  auto be32 = [](const std::vector<uint8_t>& b) {
    return (uint32_t)b[0] << 24 | (uint32_t)b[1] << 16 | (uint32_t)b[2] << 8 | b[3];
  };
  int64_t hA = (int32_t)be32(get(kv, "A.half", 4)), hB = (int32_t)be32(get(kv, "B.half", 4));
  int64_t s = be32(sr), d = hA - hB;
  int64_t lo = 1715 * d + 2 * s - 1, hi = 6 * s - 1715 * d - 1;
  printf("witness: halfA=%lld halfB=%lld d=%lld flight=%.3f cm lo=%lld hi=%lld\n", (long long)hA,
         (long long)hB, (long long)d, 17150.0 * d / s, (long long)lo, (long long)hi);
  f.push_back((uint64_t)lo, 64, p256_base);  // negative -> wraps -> constraint fails
  f.push_back((uint64_t)hi, 64, p256_base);
}

// ---------------------------------------------------------------- zk glue
using f2_p256 = Fp2<Field>;
using Elt2 = f2_p256::Elt;
using FftExt = FFTExtConvolutionFactory<Field, f2_p256>;
using RSF = ReedSolomonFactory<Field, FftExt>;
static const char kRootX[] =
    "112649224146410281873500457609690258373018840430489408729223714171582664680802";
static const char kRootY[] =
    "84087994358540907695740461427818660560182168997182378749313018254450460212908";

static std::unique_ptr<Circuit<Field>> load_circuit(const char* path) {
  auto bytes = slurp(path);
  ReadBuffer rb(bytes);
  CircuitReader<Field> cr(p256_base, P256_ID);
  auto c = cr.from_bytes(rb, false);
  if (!c) { fprintf(stderr, "bad circuit file\n"); exit(2); }
  return c;
}

int main(int argc, char** argv) {
  if (argc < 3) { fprintf(stderr, "usage: see header\n"); return 2; }
  set_log_level(ERROR);
  std::string cmd = argv[1];
  const f2_p256 p256_2(p256_base);
  const Elt2 omega = p256_2.of_string(kRootX, kRootY);
  const FftExt fft(p256_base, p256_2, omega, 1ull << 31);
  const RSF rsf(fft, p256_base);

  if (cmd == "compile") {
    set_log_level(INFO);
    double t0 = now_s();
    auto C = make_circuit();
    double t1 = now_s();
    std::vector<uint8_t> bytes;
    CircuitWriter<Field> cw(p256_base, P256_ID);
    cw.to_bytes(*C, bytes);
    spit(argv[2], bytes);
    uint8_t id[32];
    circuit_id(id, *C, p256_base);
    printf("compile: %.2f s, circuit file %zu bytes, peak RSS %.0f MB, id ", t1 - t0, bytes.size(), rss_mb());
    for (int i = 0; i < 8; ++i) printf("%02x", id[i]);
    printf("...\n");
    return 0;
  }
  if (cmd == "prove" && argc >= 5) {
    bool force = argc > 5 && !strcmp(argv[5], "--force");
    double t0 = now_s();
    auto C = load_circuit(argv[2]);
    double t1 = now_s();
    KV kv = read_kv(argv[3]);
    Dense<Field> W(1, C->ninputs);
    DenseFiller<Field> fw(W);
    fill_witness(fw, kv);
    double t2 = now_s();
    ZkProof<Field> zkpr(*C, kRate, kReq);
    Transcript tp((const uint8_t*)kLabel, strlen(kLabel), 7);
    SecureRandomEngine rng;
    bool ok;
    if (force) {
      sbzk::ForgingProver<Field, RSF> prover(*C, p256_base, rsf);
      prover.commit(zkpr, W, tp, rng);
      ok = prover.prove(zkpr, W, tp);
      printf("prove --force: proof emitted without checking the witness\n");
    } else {
      ZkProver<Field, RSF> prover(*C, p256_base, rsf);
      prover.commit(zkpr, W, tp, rng);
      ok = prover.prove(zkpr, W, tp);
    }
    double t3 = now_s();
    if (!ok) {
      printf("prove: REFUSED (witness does not satisfy the circuit) load=%.2fs witness=%.3fs prove=%.3fs rss=%.0fMB\n",
             t1 - t0, t2 - t1, t3 - t2, rss_mb());
      return 1;
    }
    std::vector<uint8_t> buf;
    zkpr.write(buf, p256_base);
    spit(argv[4], buf);
    printf("prove: OK load=%.2fs witness=%.3fs prove=%.3fs proof=%zu bytes peakRSS=%.0fMB\n", t1 - t0,
           t2 - t1, t3 - t2, buf.size(), rss_mb());
    return 0;
  }
  if (cmd == "verify" && argc >= 5) {
    double t0 = now_s();
    auto C = load_circuit(argv[2]);
    double t1 = now_s();
    KV kv = read_kv(argv[3]);
    Dense<Field> pub(1, C->npub_in);
    DenseFiller<Field> fp(pub);
    fill_public(fp, kv);
    auto buf = slurp(argv[4]);
    ZkProof<Field> zkpv(*C, kRate, kReq);
    ReadBuffer rb(buf);
    bool ok = zkpv.read(rb, p256_base);
    double t2 = now_s();
    if (ok) {
      ZkVerifier<Field, RSF> verifier(*C, rsf, kRate, kReq, p256_base);
      Transcript tv((const uint8_t*)kLabel, strlen(kLabel), 7);
      verifier.recv_commitment(zkpv, tv);
      ok = verifier.verify(zkpv, pub, tv);
    }
    double t3 = now_s();
    printf("verify: %s load=%.2fs verify=%.3fs peakRSS=%.0fMB\n", ok ? "ACCEPT" : "REJECT", t1 - t0,
           t3 - t2, rss_mb());
    return ok ? 0 : 1;
  }
  fprintf(stderr, "bad command\n");
  return 2;
}
