[profile.default]
src = "src"
test = "test"
out = "out"
optimizer = true
optimizer_runs = 1
via_ir = false
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "/private/tmp" }]
[lint]
lint_on_build = false
