#!/usr/bin/env python3
"""Parse `nargo execute` of vec/ and check server/pop/poseidon2.py against it; write vectors.json
(inputs are the fixed formulas in vec/src/main.nr, mirrored here). usage: gen_vectors.py VEC_STDOUT OUT_JSON"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "server"))
from pop import poseidon2 as p2  # noqa: E402

R = p2.R
nums = [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", pathlib.Path(sys.argv[1]).read_text().split("output:", 1)[1])]
assert len(nums) == 26, len(nums)
n = iter(nums)
take = lambda k: [next(n) for _ in range(k)]  # noqa: E731
p0, p1, h, lv, (nd,), (cc,), (hc,), ho, (seed,) = take(4), take(4), take(8), take(3), take(1), take(1), take(1), take(3), take(1)

xs = [(seed * (i + 1) + i) % R for i in range(7)]
leaf_in = [[(i * 7919 + 13) % 65536 for i in range(1024)], [32768] * 1024, [65535] * 1024]
tmpl = [[(i * 37 + k * 11 + 5) % 256 for i in range(p2.L)] for k in range(4)]
T128 = (1 << 128) - 1
half_in = [T128, seed, 3, 1, 48000, (-45042) % R, 0xDEADBEEFCAFEBABE, T128 - 1, 7,
           0x0123456789ABCDEF0123456789ABCDEF, 0xFEDCBA9876543210FEDCBA9876543210]
secret = (seed * seed + 0x1234) % R
p1_in = [seed, seed + 1, R - 1, 12345678901234567890]

got = {
    "perm0": (p2.permute([0, 1, 2, 3]), p0),
    "perm1": (p2.permute(p1_in), p1),
    **{f"hash_n_tag5_len{k}": (p2.hash_n(5, xs[:k]), h[k]) for k in range(8)},
    **{f"leaf{k}": (p2.leaf_hash_u(leaf_in[k]), lv[k]) for k in range(3)},
    "node": (p2.node_hash([lv[0], lv[1], lv[2], seed]), nd),
    "code": (p2.code_commitment_u8(*tmpl), cc),
    "half": (p2.hash_n(p2.TAG_HALF, half_in), hc),
    "half_api": (p2.half_commit(T128, seed, 3, True, 48000, -45042, 0xDEADBEEFCAFEBABE, [T128 - 1, 7],
                                bytes.fromhex("0123456789abcdef0123456789abcdef" "fedcba9876543210fedcba9876543210")), hc),
    "holder_opt3": (p2.holder_commit_opt3(secret), ho[0]),
    "holder_sp_tag11": (p2.holder_commit_sp(secret, 11), ho[1]),
    "holder_secret": (secret, ho[2]),
}
bad = [k for k, (a, b) in got.items() if a != b]
for k, (a, b) in got.items():
    print(f"{k:18s} {'ok' if a == b else 'MISMATCH'}")
hx = lambda v: [hex(x) for x in v] if isinstance(v, list) else hex(v)  # noqa: E731
json.dump({
    "note": "generated by zkmobile/hash/gen.sh from Noir oalib (nargo 1.0.0-beta.22); inputs per vec/src/main.nr",
    "seed": hex(seed),
    "perm": [{"in": hx([0, 1, 2, 3]), "out": hx(p0)}, {"in": hx(p1_in), "out": hx(p1)}],
    "hash_n_tag5": {"xs": hx(xs), "out_by_len": hx(h)},
    "leaf": {"formula": ["u_i = (i*7919+13) mod 65536", "u_i = 32768", "u_i = 65535"], "out": hx(lv)},
    "node": {"in": hx([lv[0], lv[1], lv[2], seed]), "out": hx(nd)},
    "code": {"formula": "u8 template k, index i = (i*37 + k*11 + 5) mod 256, L = 12000", "out": hx(cc)},
    "half": {"in": hx(half_in), "out": hx(hc)},
    "holder": {"secret": hx(secret), "opt3_poseidon2_hash": hx(ho[0]), "sp_tag11": hx(ho[1])},
}, open(sys.argv[2], "w"), indent=1)
print("ALL MATCH" if not bad else f"MISMATCH {bad}")
sys.exit(1 if bad else 0)
