"""Emit circuits/arrival_<tag>.circom: one JBL250 arrival, "first" rule, Freivalds-checked curve.

  python gen_circuit.py K [--mode exact|cand|core] [--nhr 2] [--W 88]

modes
  exact  claimed arrival is a candidate AND no lag before it is one (the receiver rule exactly,
         with fixed floor T0; half-rule rejects need a witness each, up to NHR)
  cand   claimed arrival is a candidate only (one-sided: a cross arrival can then only be claimed
         late, which never helps fake NEAR)
  core   Freivalds + Fiat-Shamir only (the correlation-check core, no rule)

Statement (all modes): the prover's K pairs (I_k, Q_k) equal the exact integer correlations of the
committed int16 window x with the public template (cI, cQ):
    r = Poseidon(hx, H(I, Q)), rho = Poseidon(r)
    r^(L-1) * sum_k r^k (I_k + rho Q_k) == sum_n (cI_n + rho cQ_n) r^(L-1-n) (S[n+K] - S[n]),
    S[m] = sum_{i<m} r^i x[i]                                                    (Schwartz-Zippel)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import twin  # noqa: E402

LOOK = twin.LOOK


def emit(K, mode, nhr, W, WA, L=twin.L):
    h, g = twin.fir()
    M = len(h)
    B = twin.bconst(g)
    hl = ", ".join(str(int(v)) for v in h)
    tag = f"{mode}_K{K}" + (f"_L{L}" if L != twin.L else "")
    rule = mode in ("exact", "cand")
    src = f"""pragma circom 2.1.0;
// generated by gen_circuit.py: mode={mode} L={L} K={K} M={M} NHR={nhr} W={W} WA={WA} T0={twin.T0} B={B}
include "lib.circom";

template Arrival() {{
    var L = {L};
    var K = {K};
    var M = {M};
    var HM = (M - 1) \\ 2;
    var N = K + L - 1;          // correlation support
    var NX = N + M - 1;         // + FIR support
    var LOOK = {LOOK};
    var NHR = {nhr};
    var h[M] = [{hl}];
    var B = {B};                // score >= T0  <=>  env2 * B >= E * cn2

    signal input cI[L];         // public template (masked bed), 8-bit
    signal input cQ[L];         // public Hilbert pair, same scale
    signal input x[NX];         // private int16 window
    signal input I[K];          // claimed curve
    signal input Q[K];
    signal output hx;           // commitment to x (bind to the signed rec hash)

    // ---- Fiat-Shamir challenge from the committed window and the claimed curve
    component cx = Commit16(NX);
    cx.x <== x;
    hx <== cx.h;
    component cs = HashChain(2 * K);
    for (var k = 0; k < K; k++) {{ cs.in[k] <== I[k]; cs.in[K + k] <== Q[k]; }}
    component c1 = Poseidon(2);
    c1.inputs[0] <== hx;
    c1.inputs[1] <== cs.h;
    signal r <== c1.out;
    component c2 = Poseidon(1);
    c2.inputs[0] <== r;
    signal rho <== c2.out;

    // ---- Freivalds / Schwartz-Zippel over the whole curve: O(L + K) constraints
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) {{ pw[i] <== pw[i - 1] * r; }}
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) {{ S[m] <== S[m - 1] + pw[m - 1] * x[HM + m - 1]; }}
    signal v[L];
    signal u[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {{
        v[n] <== rho * cQ[n];
        u[n] <== (cI[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + u[n] * (S[n + K] - S[n]);
    }}
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var k = 0; k < K; k++) {{
        li[k + 1] <== li[k] + pw[k] * I[k];
        lq[k + 1] <== lq[k] + pw[k] * Q[k];
    }}
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];
"""
    if rule:
        src += f"""
    // ---- normalization: E_k = sum_(m<L) y[k+m]^2, y = FIR(x) (constant taps, linear), cn2 = |cI|^2
    signal EY[N + 1];
    EY[0] <== 0;
    for (var m = 0; m < N; m++) {{
        var yl = 0;
        for (var t = 0; t < M; t++) {{ if (h[t] != 0) {{ yl += h[t] * x[m + t]; }} }}
        EY[m + 1] <== EY[m] + yl * yl;
    }}
    signal cna[L + 1];
    cna[0] <== 0;
    for (var n = 0; n < L; n++) {{ cna[n + 1] <== cna[n] + cI[n] * cI[n]; }}
    signal C[K];
    signal i2[K];
    signal env2[K];
    for (var k = 0; k < K; k++) {{
        C[k] <== (EY[k + L] - EY[k]) * cna[L];
        i2[k] <== I[k] * I[k];
        env2[k] <== i2[k] + Q[k] * Q[k];
    }}

    // ---- arrival selector: sel[k] = [k <= arr], monotone bits
    signal input arr;           // public: arrival lag in the window
    signal input sel[K + 1];
    sel[0] === 1;
    sel[1] === 1;               // arr >= 1 (needs a left neighbour)
    sel[K - 1] === 0;           // arr <= K - 2
    sel[K] === 0;
    var ssum = 0;
    for (var k = 0; k <= K; k++) {{ sel[k] * (sel[k] - 1) === 0; ssum += sel[k]; }}
    for (var k = 0; k < K; k++) {{ sel[k + 1] * (1 - sel[k]) === 0; }}
    ssum === arr + 1;

    // values at arr (e[k] = sel[k] - sel[k+1] is one-hot at arr)
    signal aE[K + 1];
    signal aM[K + 1];
    signal aP[K + 1];
    signal aC[K + 1];
    aE[0] <== 0; aM[0] <== 0; aP[0] <== 0; aC[0] <== 0;
    for (var k = 0; k < K; k++) {{
        aE[k + 1] <== aE[k] + (sel[k] - sel[k + 1]) * env2[k];
        aM[k + 1] <== aM[k] + (sel[k] - sel[k + 1]) * (k >= 1 ? env2[k - 1] : 0);
        aP[k + 1] <== aP[k] + (sel[k] - sel[k + 1]) * (k + 1 < K ? env2[k + 1] : 0);
        aC[k + 1] <== aC[k] + (sel[k] - sel[k + 1]) * C[k];
    }}
    signal envA <== aE[K];
    // candidate at arr: score >= T0, local max (>= left, > right)
    component ra0 = Range({WA});
    ra0.in <== envA * B - aC[K];
    component ra1 = Range({W});
    ra1.in <== envA - aM[K];
    component ra2 = Range({W});
    ra2.in <== envA - aP[K] - 1;
"""
    if mode == "exact":
        src += f"""
    // ---- no candidate before arr: every lag k < arr carries one reason
    //   a: score < T0 (C - env2*B - 1 >= 0)   b: env2_k <= env2_(k+1)   c: env2_k < env2_(k-1)
    //   d: half-rule reject, witnessed below (hr)
    signal input rsn[K][3];
    signal input hr_f[NHR][K];  // one-hot of a rejected lag j (all zero = unused)
    signal input hr_g[NHR][K];  // one-hot of its veto lag m, j <= m <= j + LOOK, env2_m > 4 env2_j
    signal p1[K];
    signal p2[K];
    signal p3[K];
    signal p4[K];
    component rk[K];
    for (var k = 0; k < K; k++) {{
        rsn[k][0] * (rsn[k][0] - 1) === 0;
        rsn[k][1] * (rsn[k][1] - 1) === 0;
        rsn[k][2] * (rsn[k][2] - 1) === 0;
        var hs = 0;
        for (var w = 0; w < NHR; w++) {{ hs += hr_f[w][k]; }}
        rsn[k][0] + rsn[k][1] + rsn[k][2] + hs === sel[k + 1];      // exactly one reason iff k < arr
        p1[k] <== rsn[k][0] * (C[k] - env2[k] * B - 1);
        p2[k] <== rsn[k][1] * (k + 1 < K ? env2[k + 1] - env2[k] : -1);
        p3[k] <== rsn[k][2] * (k >= 1 ? env2[k - 1] - env2[k] - 1 : 0);
        // half rule at arr: lags arr..arr+LOOK must satisfy env2_m <= 4 env2_arr
        var la = (1 - sel[k + 1]) - (k >= LOOK ? 1 - sel[k - LOOK] : 0);
        p4[k] <== la * (4 * envA - env2[k]);
        rk[k] = Range({W});
        rk[k].in <== p1[k] + p2[k] + p3[k] + p4[k];
    }}
    // half-rule reject witnesses
    signal fj[NHR][K + 1];
    signal gm[NHR][K + 1];
    signal used[NHR];
    component rh0[NHR];
    component rh1[NHR];
    component rh2[NHR];
    for (var w = 0; w < NHR; w++) {{
        var fs = 0;
        var gs = 0;
        var fi = 0;
        var gi = 0;
        fj[w][0] <== 0;
        gm[w][0] <== 0;
        for (var k = 0; k < K; k++) {{
            hr_f[w][k] * (hr_f[w][k] - 1) === 0;
            hr_g[w][k] * (hr_g[w][k] - 1) === 0;
            fs += hr_f[w][k]; gs += hr_g[w][k];
            fi += hr_f[w][k] * k; gi += hr_g[w][k] * k;
            fj[w][k + 1] <== fj[w][k] + hr_f[w][k] * env2[k];
            gm[w][k + 1] <== gm[w][k] + hr_g[w][k] * env2[k];
        }}
        used[w] <== fs;
        used[w] * (used[w] - 1) === 0;
        gs === used[w];
        rh0[w] = Range(9);
        rh0[w].in <== gi - fi;                     // m >= j
        rh1[w] = Range(9);
        rh1[w].in <== used[w] * LOOK - (gi - fi);  // m <= j + LOOK
        rh2[w] = Range({W});
        rh2[w].in <== used[w] * (gm[w][K] - 4 * fj[w][K] - 1);
    }}
"""
    elif mode == "cand":
        src += f"""
    // ---- half rule at arr only (lags arr..arr+LOOK): env2_m <= 4 env2_arr
    signal p4[K];
    component rk[K];
    for (var k = 0; k < K; k++) {{
        var la = (1 - sel[k + 1]) - (k >= LOOK ? 1 - sel[k - LOOK] : 0);
        p4[k] <== la * (4 * envA - env2[k]);
        rk[k] = Range({W});
        rk[k].in <== p4[k];
    }}
"""
    pubs = "cI, cQ, arr" if rule else "cI, cQ"
    src += f"""}}

component main {{public [{pubs}]}} = Arrival();
"""
    out = HERE / "circuits" / f"arrival_{tag}.circom"
    out.write_text(src)
    print(out)
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("K", type=int)
    ap.add_argument("--mode", default="exact", choices=("exact", "cand", "core"))
    ap.add_argument("--nhr", type=int, default=2)
    ap.add_argument("--W", type=int, default=88)
    ap.add_argument("--WA", type=int, default=96)
    ap.add_argument("--L", type=int, default=twin.L)
    a = ap.parse_args()
    emit(a.K, a.mode, a.nhr, a.W, a.WA, a.L)
