"""Chain attester (worldid spec 01 §4, §8.2): P-256 over a sha256 digest, raw r||s, no low-s normalization.

Separate from the SBcred3 issuer key. POP_ATTEST_KEY_FILE (default data/attest.pem) is loaded if it exists
(SEC1 or PKCS8 PEM), autogenerated 0600 only when missing. Never regenerate once a Safe pins its qx/qy.
"""
from __future__ import annotations

import hashlib
import logging
import os
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed, decode_dss_signature

log = logging.getLogger("pop")

MAGIC_POP2 = b"POP2"


def load_key(path: str | Path, autogen: bool = True) -> ec.EllipticCurvePrivateKey:
    p = Path(path)
    if p.exists():
        sk = serialization.load_pem_private_key(p.read_bytes(), password=None)
        if not isinstance(sk, ec.EllipticCurvePrivateKey) or not isinstance(sk.curve, ec.SECP256R1):
            raise ValueError(f"{p}: not a P-256 key")
        return sk
    if not autogen:
        raise FileNotFoundError(str(p))
    sk = ec.generate_private_key(ec.SECP256R1())
    p.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(sk.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                 serialization.NoEncryption()))
    log.warning("generated a NEW chain attest key at %s (back it up; Safes pin its qx/qy)", p)
    return sk


def public(sk: ec.EllipticCurvePrivateKey) -> dict:
    n = sk.public_key().public_numbers()
    return {"alg": "p256", "qx": "0x%064x" % n.x, "qy": "0x%064x" % n.y}


def _b(x: str | bytes, n: int, what: str) -> bytes:
    raw = bytes.fromhex(x[2:] if x[:2] in ("0x", "0X") else x) if isinstance(x, str) else x
    if len(raw) != n:
        raise ValueError(f"{what} must be {n} bytes")
    return raw


def preimage(tag: bytes, chain_id: int, consumer, ctx_hash, pair_tag, dev_a, dev_b, expiry: int) -> bytes:
    """tag(11) | u256 chainId | consumer(20) | ctxHash | pairTag | devA | devB | u64 expiry BE (199 B for 11 B tags)."""
    return (tag + chain_id.to_bytes(32, "big") + _b(consumer, 20, "consumer") + _b(ctx_hash, 32, "ctx_hash")
            + _b(pair_tag, 32, "pair_tag") + _b(dev_a, 32, "dev_a") + _b(dev_b, 32, "dev_b")
            + expiry.to_bytes(8, "big"))


def tagged_digest(tag: bytes, chain_id: int, consumer, ctx_hash, pair_tag, dev_a, dev_b, expiry: int) -> bytes:
    return hashlib.sha256(preimage(tag, chain_id, consumer, ctx_hash, pair_tag, dev_a, dev_b, expiry)).digest()


def sign(sk: ec.EllipticCurvePrivateKey, digest: bytes) -> tuple[bytes, bytes]:
    r, s = decode_dss_signature(sk.sign(digest, ec.ECDSA(Prehashed(hashes.SHA256()))))
    return r.to_bytes(32, "big"), s.to_bytes(32, "big")


def tail(pair_tag, dev_a, dev_b, expiry: int, r: bytes, s: bytes) -> bytes:
    """172 B: pairTag | devA | devB | expiry(8) | r | s | "POP2" (what PopAttestationVerifier reads)."""
    t = (_b(pair_tag, 32, "pair_tag") + _b(dev_a, 32, "dev_a") + _b(dev_b, 32, "dev_b") + expiry.to_bytes(8, "big")
         + r + s + MAGIC_POP2)
    assert len(t) == 172
    return t


def presence_frame(presence: bytes) -> bytes:
    """What PopSafeGuard expects after the owner sigs: presence | u32 BE len | "POPV"."""
    return presence + len(presence).to_bytes(4, "big") + b"POPV"
