import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    kotlin("plugin.compose")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("com.android.application")
}

/** Writes PopBuildConfig.kt (commonMain has no BuildConfig). */
abstract class GenPopBuildConfig : DefaultTask() {
    @get:Input abstract val serverUrl: Property<String>
    @get:Input abstract val webSameOrigin: Property<Boolean>
    @get:OutputDirectory abstract val outDir: DirectoryProperty

    @TaskAction fun gen() {
        val url = serverUrl.get().trim().trimEnd('/')
        require(Regex("^https?://[^\\s\"$]+$").matches(url)) { "pop.serverUrl: bad URL '$url'" }
        val f = outDir.file("com/enconomy/pop/PopBuildConfig.kt").get().asFile
        f.parentFile.mkdirs()
        f.writeText(
            "package com.enconomy.pop\n\n" +
                "/** Generated by :composeApp:genPopBuildConfig. */\n" +
                "object PopBuildConfig {\n    const val SERVER_URL = \"$url\"\n" +
                "    /** Web only: talk to the origin that served the page (build_web.sh server mode). */\n" +
                "    const val WEB_SAME_ORIGIN = ${webSameOrigin.get()}\n}\n",
        )
    }
}

// ./gradlew assembleDebug -Ppop.serverUrl=https://...  or  POP_SERVER_URL=https://... ./gradlew assembleDebug
val genPopBuildConfig = tasks.register<GenPopBuildConfig>("genPopBuildConfig") {
    serverUrl.set(
        providers.gradleProperty("pop.serverUrl")
            .orElse(providers.environmentVariable("POP_SERVER_URL"))
            .orElse("http://10.0.2.2:8000"),
    )
    webSameOrigin.set(providers.gradleProperty("pop.webSameOrigin").map { it == "true" || it == "1" }.orElse(false))
    outDir.set(layout.buildDirectory.dir("generated/popBuildConfig/commonMain/kotlin"))
}

/** Writes the absolute commonTest/resources path for native tests (the simulator reads the host FS). */
abstract class GenTestResourceDir : DefaultTask() {
    @get:Input abstract val resDir: Property<String>
    @get:OutputDirectory abstract val outDir: DirectoryProperty

    @TaskAction fun gen() {
        val f = outDir.file("com/enconomy/pop/TestResourceDir.kt").get().asFile
        f.parentFile.mkdirs()
        f.writeText(
            "package com.enconomy.pop\n\n" +
                "/** Generated by :composeApp:genTestResourceDir. */\n" +
                "internal const val TEST_RESOURCE_DIR = \"${resDir.get()}\"\n",
        )
    }
}

val genTestResourceDir = tasks.register<GenTestResourceDir>("genTestResourceDir") {
    resDir.set(layout.projectDirectory.dir("src/commonTest/resources").asFile.absolutePath)
    outDir.set(layout.buildDirectory.dir("generated/testResourceDir/iosTest/kotlin"))
}

// ---- option A prover (app/zkprove: ACVM witness + Barretenberg UltraHonk, Noir circuit oaN_s48) ----
// Native builds are heavy and need the NDK / Xcode: they run only with -Ppop.buildProver=true (or by hand,
// app/zkprove/scripts/build_{android,ios}.sh). Otherwise the last dist/ output is used; without it the app builds
// and runs v2 without on-phone proofs (ProverLib.available = false). The whole gradle run goes under heavy.sh
// (not reentrant, so these tasks don't take the lock themselves).
val proverDir = rootProject.file("zkprove")
val buildProver = providers.gradleProperty("pop.buildProver").map { it == "true" }.orElse(false)

val buildProverAndroid = tasks.register<Exec>("buildProverAndroid") {
    description = "app/zkprove -> zkprove/dist/android/arm64-v8a/libzkprove.so (cargo-ndk, heavy)"
    workingDir = proverDir
    commandLine(proverDir.resolve("scripts/build_android.sh").absolutePath)
    onlyIf { buildProver.get() }
}

val buildProverIos = tasks.register<Exec>("buildProverIos") {
    description = "app/zkprove -> zkprove/dist/ios/ZkProve.xcframework (heavy)"
    workingDir = proverDir
    commandLine(proverDir.resolve("scripts/build_ios.sh").absolutePath)
    onlyIf { buildProver.get() }
}

/** jniLibs/arm64-v8a/libzkprove.so, generated so the 25 MB .so never sits in src/. */
val copyProverSo = tasks.register<Sync>("copyProverSo") {
    dependsOn(buildProverAndroid)
    from(proverDir.resolve("dist/android")) { include("arm64-v8a/libzkprove.so") }
    into(layout.buildDirectory.dir("generated/proverJniLibs"))
}

val proverXcf = proverDir.resolve("dist/ios/ZkProve.xcframework")
val iosSlices = mapOf("iosArm64" to "ios-arm64", "iosSimulatorArm64" to "ios-arm64-simulator")
val iosProver = buildProver.get() || iosSlices.values.all { proverXcf.resolve("$it/libzkprove.a").isFile }

kotlin {
    androidTarget {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    listOf(iosArm64(), iosSimulatorArm64()).forEach {
        it.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
        it.compilations.getByName("main").cinterops.create("popmem") {
            definitionFile.set(project.file("src/nativeInterop/cinterop/popmem.def"))
        }
        if (iosProver) it.compilations.getByName("main").cinterops.create("zkprove") {
            definitionFile.set(project.file("src/nativeInterop/cinterop/zkprove.def"))
            includeDirs(proverDir.resolve("include"))
            extraOpts("-libraryPath", proverXcf.resolve(iosSlices.getValue(it.name)).absolutePath)
        }
    }
    // Web build (Kotlin/Wasm): ./gradlew :composeApp:wasmJsBrowserDistribution -Ppop.serverUrl=https://pop.enconomy.dev
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("popweb")
        compilerOptions { optIn.add("kotlin.js.ExperimentalWasmJsInterop") }
        browser { commonWebpackConfig { outputFileName = "popweb.js" } }
        binaries.executable()
    }
    compilerOptions { freeCompilerArgs.add("-Xexpect-actual-classes") }

    sourceSets {
        commonMain {
            kotlin.srcDir(genPopBuildConfig.flatMap { it.outDir })
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            implementation("io.ktor:ktor-client-core:3.2.3")
            implementation("org.kotlincrypto.hash:sha3:0.8.0")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
            implementation("io.ktor:ktor-client-mock:3.2.3")
        }
        androidMain.dependencies {
            implementation("androidx.activity:activity-compose:1.10.1")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
            implementation("io.ktor:ktor-client-okhttp:3.2.3")
            implementation("com.google.zxing:core:3.5.3")
            implementation("androidx.camera:camera-camera2:1.4.2")
            implementation("androidx.camera:camera-lifecycle:1.4.2")
            implementation("androidx.camera:camera-view:1.4.2")
            implementation("com.google.mlkit:barcode-scanning:17.3.0")
        }
        wasmJsMain.dependencies {
            implementation("io.ktor:ktor-client-js:3.2.3")
            implementation(npm("@noble/curves", "1.9.7"))
            implementation(npm("@noble/hashes", "1.8.0"))
            implementation(npm("qrcode-generator", "1.4.4"))
            implementation(npm("jsqr", "1.4.0"))
        }
        iosMain.dependencies {
            implementation("io.ktor:ktor-client-darwin:3.2.3")
        }
        iosMain {
            kotlin.srcDir(if (iosProver) "src/iosProver/kotlin" else "src/iosNoProver/kotlin")
        }
        iosTest {
            kotlin.srcDir(genTestResourceDir.flatMap { it.outDir })
        }
    }
}

// settings.gradle.kts has FAIL_ON_PROJECT_REPOS: node / yarn / binaryen come from the ivy repos declared there,
// so the Kotlin/Wasm plugins must not add their own download repos.
@OptIn(ExperimentalWasmDsl::class)
fun noWasmDownloadRepos(p: Project) {
    p.plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsRootPlugin> {
        p.extensions.findByType<org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsEnvSpec>()?.downloadBaseUrl?.set(null as String?)
    }
    p.plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsPlugin> {
        p.extensions.findByType<org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsEnvSpec>()?.downloadBaseUrl?.set(null as String?)
    }
    p.plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin> {
        p.extensions.findByType<org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootEnvSpec>()?.downloadBaseUrl?.set(null as String?)
    }
    p.plugins.withType<org.jetbrains.kotlin.gradle.targets.wasm.binaryen.BinaryenPlugin> {
        p.extensions.findByType<org.jetbrains.kotlin.gradle.targets.wasm.binaryen.BinaryenEnvSpec>()?.downloadBaseUrl?.set(null as String?)
    }
}
noWasmDownloadRepos(rootProject)
noWasmDownloadRepos(project)

compose.resources {
    packageOfResClass = "com.enconomy.pop.res"
    publicResClass = false
    generateResClass = always
}

// opt-in heavy prover tests on the simulator: POP_ZK_KEYS=<dir with oa2t_s48.pk.zst>
tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest>().configureEach {
    providers.environmentVariable("POP_ZK_KEYS").orNull?.let { environment("SIMCTL_CHILD_POP_ZK_KEYS", it) }
}

tasks.matching { it.name.startsWith("cinteropZkprove") }.configureEach { dependsOn(buildProverIos) }

android {
    namespace = "com.enconomy.pop"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.enconomy.pop"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "0.1"
        ndk { abiFilters += "arm64-v8a" }
        // libpop_aaudio.so needs input presets (API 28); AAudioNative checks SDK_INT before loading it.
        externalNativeBuild { cmake { arguments += "-DANDROID_PLATFORM=android-28" } }
    }
    ndkVersion = "28.2.13676358"
    externalNativeBuild {
        cmake {
            path = file("src/androidMain/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }
    buildTypes {
        // debug key: hackathon installs; release = optimized, non-debuggable ART (the prover bench build)
        getByName("release") { isMinifyEnabled = false; signingConfig = signingConfigs.getByName("debug") }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    packaging {
        resources.excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }
    // commonTest/resources (DSP fixtures) on the JVM unit-test classpath; read via readTestResource().
    sourceSets["test"].resources.srcDirs("src/commonTest/resources", "src/commonMain/composeResources")
    sourceSets["main"].jniLibs.srcDir(layout.buildDirectory.dir("generated/proverJniLibs"))
}

tasks.matching { it.name.startsWith("merge") && it.name.endsWith("JniLibFolders") }.configureEach { dependsOn(copyProverSo) }
