import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    kotlin("plugin.compose")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("com.android.application")
}

/** Writes PopBuildConfig.kt (commonMain has no BuildConfig). */
abstract class GenPopBuildConfig : DefaultTask() {
    @get:Input abstract val serverUrl: Property<String>
    @get:OutputDirectory abstract val outDir: DirectoryProperty

    @TaskAction fun gen() {
        val url = serverUrl.get().trim().trimEnd('/')
        require(Regex("^https?://[^\\s\"$]+$").matches(url)) { "pop.serverUrl: bad URL '$url'" }
        val f = outDir.file("com/enconomy/pop/PopBuildConfig.kt").get().asFile
        f.parentFile.mkdirs()
        f.writeText(
            "package com.enconomy.pop\n\n" +
                "/** Generated by :composeApp:genPopBuildConfig. */\n" +
                "object PopBuildConfig {\n    const val SERVER_URL = \"$url\"\n}\n",
        )
    }
}

// ./gradlew assembleDebug -Ppop.serverUrl=https://...  or  POP_SERVER_URL=https://... ./gradlew assembleDebug
val genPopBuildConfig = tasks.register<GenPopBuildConfig>("genPopBuildConfig") {
    serverUrl.set(
        providers.gradleProperty("pop.serverUrl")
            .orElse(providers.environmentVariable("POP_SERVER_URL"))
            .orElse("http://10.0.2.2:8000"),
    )
    outDir.set(layout.buildDirectory.dir("generated/popBuildConfig/commonMain/kotlin"))
}

kotlin {
    androidTarget {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    compilerOptions { freeCompilerArgs.add("-Xexpect-actual-classes") }

    sourceSets {
        commonMain {
            kotlin.srcDir(genPopBuildConfig.flatMap { it.outDir })
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            implementation("io.ktor:ktor-client-core:3.2.3")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
            implementation("io.ktor:ktor-client-mock:3.2.3")
        }
        androidMain.dependencies {
            implementation("androidx.activity:activity-compose:1.10.1")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
            implementation("io.ktor:ktor-client-okhttp:3.2.3")
            implementation("com.google.zxing:core:3.5.3")
            implementation("androidx.camera:camera-camera2:1.4.2")
            implementation("androidx.camera:camera-lifecycle:1.4.2")
            implementation("androidx.camera:camera-view:1.4.2")
            implementation("com.google.mlkit:barcode-scanning:17.3.0")
        }
    }
}

android {
    namespace = "com.enconomy.pop"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.enconomy.pop"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "0.1"
    }
    buildTypes {
        getByName("release") { isMinifyEnabled = false }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    packaging {
        resources.excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }
    // commonTest/resources (DSP fixtures) on the JVM unit-test classpath; read via readTestResource().
    sourceSets["test"].resources.srcDirs("src/commonTest/resources")
}
