"""Writes commonMain/.../zk/Poseidon7Params.kt from the spike's params_t5.json / params_t16.json.

Run: $PY gen_constants.py   ($PY = research/proximity-echo/.venv/bin/python3). Reads research/ only.
"""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[6]
SRC = REPO / "research/sound-bound/spikes/zk/optionA-v2/poseidon7"
OUT = REPO / "app/composeApp/src/commonMain/kotlin/com/enconomy/pop/zk/Poseidon7Params.kt"
P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF


def h64(s):
    v = int(s, 16)
    assert 0 <= v < P
    return "%064x" % v


def block(t):
    raw = (SRC / f"params_t{t}.json").read_bytes()
    d = json.loads(raw)
    assert int(d["p"], 16) == P and d["t"] == t and d["alpha"] == 7
    rf, rp = d["R_F"], d["R_P"]
    assert len(d["C"]) == (rf + rp) * t and len(d["M"]) == t and all(len(r) == t for r in d["M"])
    rows_c = [d["C"][r * t:(r + 1) * t] for r in range(rf + rp)]
    lines = [f"    // params_t{t}.json sha256 {hashlib.sha256(raw).hexdigest()}",
             f"    val T{t} = Poseidon7.Params(",
             f"        t = {t}, rf = {rf}, rp = {rp},",
             "        c = arrayOf("]
    lines += ['            "' + "".join(h64(c) for c in row) + '",' for row in rows_c]
    lines += ["        ),", "        m = arrayOf("]
    lines += ['            "' + "".join(h64(v) for v in row) + '",' for row in d["M"]]
    lines += ["        ),", "    )"]
    return lines


def main():
    out = ["package com.enconomy.pop.zk", "",
           "// Generated by commonTest/resources/zk/tools/gen_constants.py from",
           "// research/sound-bound/spikes/zk/optionA-v2/poseidon7/params_t{5,16}.json. Do not edit.",
           "// c: one string per round (t × 64 hex digits, cell order); m: one string per MDS row.",
           "", "internal object Poseidon7Params {"]
    out += block(5)
    out += [""]
    out += block(16)
    out += ["}", ""]
    OUT.write_text("\n".join(out))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
