pragma circom 2.1.0;
// generated by gen_circuit.py: mode=cand L=12000 K=1024 M=63 NHR=2 W=88 WA=96 T0=0.09 B=4474747
include "lib.circom";

template Arrival() {
    var L = 12000;
    var K = 1024;
    var M = 63;
    var HM = (M - 1) \ 2;
    var N = K + L - 1;          // correlation support
    var NX = N + M - 1;         // + FIR support
    var LOOK = 240;
    var NHR = 2;
    var h[M] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 4, -1, 0, 2, -7, 0, -5, -13, 0, -19, -13, 0, -45, 27, 127, 27, -45, 0, -13, -19, 0, -13, -5, 0, -7, 2, 0, -1, 4, 0, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    var B = 4474747;                // score >= T0  <=>  env2 * B >= E * cn2

    signal input cI[L];         // public template (masked bed), 8-bit
    signal input cQ[L];         // public Hilbert pair, same scale
    signal input x[NX];         // private int16 window
    signal input I[K];          // claimed curve
    signal input Q[K];
    signal output hx;           // commitment to x (bind to the signed rec hash)

    // ---- Fiat-Shamir challenge from the committed window and the claimed curve
    component cx = Commit16(NX);
    cx.x <== x;
    hx <== cx.h;
    component cs = HashChain(2 * K);
    for (var k = 0; k < K; k++) { cs.in[k] <== I[k]; cs.in[K + k] <== Q[k]; }
    component c1 = Poseidon(2);
    c1.inputs[0] <== hx;
    c1.inputs[1] <== cs.h;
    signal r <== c1.out;
    component c2 = Poseidon(1);
    c2.inputs[0] <== r;
    signal rho <== c2.out;

    // ---- Freivalds / Schwartz-Zippel over the whole curve: O(L + K) constraints
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) { pw[i] <== pw[i - 1] * r; }
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) { S[m] <== S[m - 1] + pw[m - 1] * x[HM + m - 1]; }
    signal v[L];
    signal u[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {
        v[n] <== rho * cQ[n];
        u[n] <== (cI[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + u[n] * (S[n + K] - S[n]);
    }
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var k = 0; k < K; k++) {
        li[k + 1] <== li[k] + pw[k] * I[k];
        lq[k + 1] <== lq[k] + pw[k] * Q[k];
    }
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];

    // ---- normalization: E_k = sum_(m<L) y[k+m]^2, y = FIR(x) (constant taps, linear), cn2 = |cI|^2
    signal EY[N + 1];
    EY[0] <== 0;
    for (var m = 0; m < N; m++) {
        var yl = 0;
        for (var t = 0; t < M; t++) { if (h[t] != 0) { yl += h[t] * x[m + t]; } }
        EY[m + 1] <== EY[m] + yl * yl;
    }
    signal cna[L + 1];
    cna[0] <== 0;
    for (var n = 0; n < L; n++) { cna[n + 1] <== cna[n] + cI[n] * cI[n]; }
    signal C[K];
    signal i2[K];
    signal env2[K];
    for (var k = 0; k < K; k++) {
        C[k] <== (EY[k + L] - EY[k]) * cna[L];
        i2[k] <== I[k] * I[k];
        env2[k] <== i2[k] + Q[k] * Q[k];
    }

    // ---- arrival selector: sel[k] = [k <= arr], monotone bits
    signal input arr;           // public: arrival lag in the window
    signal input sel[K + 1];
    sel[0] === 1;
    sel[1] === 1;               // arr >= 1 (needs a left neighbour)
    sel[K - 1] === 0;           // arr <= K - 2
    sel[K] === 0;
    var ssum = 0;
    for (var k = 0; k <= K; k++) { sel[k] * (sel[k] - 1) === 0; ssum += sel[k]; }
    for (var k = 0; k < K; k++) { sel[k + 1] * (1 - sel[k]) === 0; }
    ssum === arr + 1;

    // values at arr (e[k] = sel[k] - sel[k+1] is one-hot at arr)
    signal aE[K + 1];
    signal aM[K + 1];
    signal aP[K + 1];
    signal aC[K + 1];
    aE[0] <== 0; aM[0] <== 0; aP[0] <== 0; aC[0] <== 0;
    for (var k = 0; k < K; k++) {
        aE[k + 1] <== aE[k] + (sel[k] - sel[k + 1]) * env2[k];
        aM[k + 1] <== aM[k] + (sel[k] - sel[k + 1]) * (k >= 1 ? env2[k - 1] : 0);
        aP[k + 1] <== aP[k] + (sel[k] - sel[k + 1]) * (k + 1 < K ? env2[k + 1] : 0);
        aC[k + 1] <== aC[k] + (sel[k] - sel[k + 1]) * C[k];
    }
    signal envA <== aE[K];
    // candidate at arr: score >= T0, local max (>= left, > right)
    component ra0 = Range(96);
    ra0.in <== envA * B - aC[K];
    component ra1 = Range(88);
    ra1.in <== envA - aM[K];
    component ra2 = Range(88);
    ra2.in <== envA - aP[K] - 1;

    // ---- half rule at arr only (lags arr..arr+LOOK): env2_m <= 4 env2_arr
    signal p4[K];
    component rk[K];
    for (var k = 0; k < K; k++) {
        var la = (1 - sel[k + 1]) - (k >= LOOK ? 1 - sel[k - LOOK] : 0);
        p4[k] <== la * (4 * envA - env2[k]);
        rk[k] = Range(88);
        rk[k].in <== p4[k];
    }
}

component main {public [cI, cQ, arr]} = Arrival();
