pragma circom 2.1.0;
// generated by gen_circuit.py: mode=core L=12000 K=19200 M=63 NHR=2 W=88 WA=96 T0=0.09 B=4474747
include "lib.circom";

template Arrival() {
    var L = 12000;
    var K = 19200;
    var M = 63;
    var HM = (M - 1) \ 2;
    var N = K + L - 1;          // correlation support
    var NX = N + M - 1;         // + FIR support
    var LOOK = 240;
    var NHR = 2;
    var h[M] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 4, -1, 0, 2, -7, 0, -5, -13, 0, -19, -13, 0, -45, 27, 127, 27, -45, 0, -13, -19, 0, -13, -5, 0, -7, 2, 0, -1, 4, 0, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    var B = 4474747;                // score >= T0  <=>  env2 * B >= E * cn2

    signal input cI[L];         // public template (masked bed), 8-bit
    signal input cQ[L];         // public Hilbert pair, same scale
    signal input x[NX];         // private int16 window
    signal input I[K];          // claimed curve
    signal input Q[K];
    signal output hx;           // commitment to x (bind to the signed rec hash)

    // ---- Fiat-Shamir challenge from the committed window and the claimed curve
    component cx = Commit16(NX);
    cx.x <== x;
    hx <== cx.h;
    component cs = HashChain(2 * K);
    for (var k = 0; k < K; k++) { cs.in[k] <== I[k]; cs.in[K + k] <== Q[k]; }
    component c1 = Poseidon(2);
    c1.inputs[0] <== hx;
    c1.inputs[1] <== cs.h;
    signal r <== c1.out;
    component c2 = Poseidon(1);
    c2.inputs[0] <== r;
    signal rho <== c2.out;

    // ---- Freivalds / Schwartz-Zippel over the whole curve: O(L + K) constraints
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) { pw[i] <== pw[i - 1] * r; }
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) { S[m] <== S[m - 1] + pw[m - 1] * x[HM + m - 1]; }
    signal v[L];
    signal u[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {
        v[n] <== rho * cQ[n];
        u[n] <== (cI[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + u[n] * (S[n + K] - S[n]);
    }
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var k = 0; k < K; k++) {
        li[k + 1] <== li[k] + pw[k] * I[k];
        lq[k + 1] <== lq[k] + pw[k] * Q[k];
    }
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];
}

component main {public [cI, cQ]} = Arrival();
