pragma circom 2.2.3;
// generated by gen_circuit.py: delta=48 (1 ms) K=97 NS=12158 NLS=13 NP=12062 NLP=13
// window=w400 [-7200, +12000] L=12000 M=63 HM=31 B=4474747 W=96 sig=False
include "oa2lib.circom";


template OA2() {
    var L = 12000;
    var K = 97;
    var DELTA = 48;
    var HM = 31;
    var M = 63;
    var NS = 12158;
    var NP = 12062;
    var NLS = 13;
    var NLP = 13;
    var WPRE = 7200;
    var WPOST = 12000;
    var B = 4474747;
    var h[M] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 4, -1, 0, 2, -7, 0, -5, -13, 0, -19, -13, 0, -45, 27, 127, 27, -45, 0, -13, -19, 0, -13, -5, 0, -7, 2, 0, -1, 4, 0, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0];

    // ---------------- public
    signal input nonceHi;
    signal input nonceLo;
    signal input attempt;
    signal input roleB;
    signal input codeHi;          // code_commit (SHA-256 of the int8 templates) as 2 x 128-bit limbs
    signal input codeLo;
    signal input cIs[L];          // own template (self arrival), 8-bit; verifier derives it
    signal input cQs[L];
    signal input cIp[L];          // partner template
    signal input cQp[L];
    signal output halfCommit;
    // ---------------- public (audio-only variant: the signed fields are given in the clear)
    signal input recRoot;
    signal input pSelf;
    signal input pPartner;
    signal input salt;
    // ---------------- private: recording openings, claimed curve, arrival selector
    signal input xs[NLS][1024];
    signal input chS[NLS][6][4];
    signal input leafS;
    signal input xp[NLP][1024];
    signal input chP[NLP][6][4];
    signal input leafP;
    signal input I[K];
    signal input Q[K];
    signal input u[K];            // u[j] = [j < a_self - (p_self - delta)]

    roleB * (roleB - 1) === 0;
    signal input aSelf;
    signal input aPartner;

    // ================= (2) open the recording: self and partner regions
    // self region starts at the leaf holding p_self - delta - HM; oS = offset inside that leaf
    signal oS <== pSelf - DELTA - HM - 1024 * leafS;
    component oSb = Num2Bits(10); oSb.in <== oS;
    component opS = OpenLeaves(NLS);
    opS.x <== xs; opS.first <== leafS; opS.ch <== chS; opS.root <== recRoot;
    signal oP <== aPartner - HM - 1024 * leafP;
    component oPb = Num2Bits(10); oPb.in <== oP;
    component opP = OpenLeaves(NLP);
    opP.x <== xp; opP.first <== leafP; opP.ch <== chP; opP.root <== recRoot;
    // shift to the window start (barrel shifter over the 10 offset bits)
    component shS = Barrel1024(NLS * 1024, NS);
    for (var i = 0; i < NLS; i++) { for (var j = 0; j < 1024; j++) { shS.in[1024 * i + j] <== xs[i][j]; } }
    shS.bits <== oSb.out;
    component shP = Barrel1024(NLP * 1024, NP);
    for (var i = 0; i < NLP; i++) { for (var j = 0; j < 1024; j++) { shP.in[1024 * i + j] <== xp[i][j]; } }
    shP.bits <== oPb.out;
    // shS.out[i] = x[p_self - delta - HM + i];  shP.out[i] = x[a_partner - HM + i]

    // ================= (3) Fiat-Shamir challenge over everything committed, Freivalds on the self curve
    component fs = Sponge16(206, 52739);
    fs.in[0] <== nonceHi; fs.in[1] <== nonceLo; fs.in[2] <== attempt; fs.in[3] <== roleB;
    fs.in[4] <== recRoot; fs.in[5] <== pSelf; fs.in[6] <== pPartner; fs.in[7] <== DELTA;
    fs.in[8] <== aSelf; fs.in[9] <== aPartner; fs.in[10] <== codeHi; fs.in[11] <== codeLo;
    for (var j = 0; j < K; j++) { fs.in[12 + j] <== I[j]; fs.in[12 + K + j] <== Q[j]; }
    signal r <== fs.o1;
    signal rho <== fs.o2;
    var N = K + L - 1;
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) { pw[i] <== pw[i - 1] * r; }
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) { S[m] <== S[m - 1] + pw[m - 1] * shS.out[HM + m - 1]; }
    signal v[L];
    signal uu[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {
        v[n] <== rho * cQs[n];
        uu[n] <== (cIs[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + uu[n] * (S[n + K] - S[n]);
    }
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var j = 0; j < K; j++) {
        li[j + 1] <== li[j] + pw[j] * I[j];
        lq[j + 1] <== lq[j] + pw[j] * Q[j];
    }
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];

    // ================= normalization (self): E_j = sum_(m<L) y[j+m]^2, y = FIR(x); cn2 = |cI|^2
    signal EY[N + 1];
    EY[0] <== 0;
    for (var m = 0; m < N; m++) {
        var yl = 0;
        for (var t = 0; t < M; t++) { if (h[t] != 0) { yl += h[t] * shS.out[m + t]; } }
        EY[m + 1] <== EY[m] + yl * yl;
    }
    signal cna[L + 1];
    cna[0] <== 0;
    for (var n = 0; n < L; n++) { cna[n + 1] <== cna[n] + cIs[n] * cIs[n]; }

    // ================= (4) self arrival: first lag >= bar in [p_self - delta, p_self + delta]
    u[K - 1] === 0;
    var usum = 0;
    for (var j = 0; j < K; j++) {
        u[j] * (u[j] - 1) === 0;
        if (j > 0) { u[j] * (1 - u[j - 1]) === 0; }
        usum += u[j];
    }
    usum === aSelf - pSelf + DELTA;         // => a_self in [p_self - delta, p_self + delta]
    signal C[K];
    signal i2[K];
    signal env2[K];
    signal pu[K];
    signal pe[K];
    component rk[K];
    for (var j = 0; j < K; j++) {
        C[j] <== (EY[j + L] - EY[j]) * cna[L];
        i2[j] <== I[j] * I[j];
        env2[j] <== i2[j] + Q[j] * Q[j];
        var D = C[j] - B * env2[j];         // D > 0  <=>  score < bar
        var e = (j == 0 ? 1 : u[j - 1]) - u[j];   // one-hot at the arrival
        pu[j] <== u[j] * (D - 1);            // before the arrival: D - 1 >= 0
        pe[j] <== e * D;                     // at the arrival: -D >= 0
        rk[j] = Range(96);
        rk[j].in <== pu[j] - pe[j];
    }

    // ================= (5) partner arrival: one lag, score >= bar, inside the pinned window
    signal ipI[L + 1];
    signal ipQ[L + 1];
    ipI[0] <== 0;
    ipQ[0] <== 0;
    for (var n = 0; n < L; n++) {
        ipI[n + 1] <== ipI[n] + cIp[n] * shP.out[HM + n];
        ipQ[n + 1] <== ipQ[n] + cQp[n] * shP.out[HM + n];
    }
    signal EP[L + 1];
    EP[0] <== 0;
    for (var m = 0; m < L; m++) {
        var yl = 0;
        for (var t = 0; t < M; t++) { if (h[t] != 0) { yl += h[t] * shP.out[m + t]; } }
        EP[m + 1] <== EP[m] + yl * yl;
    }
    signal cnp[L + 1];
    cnp[0] <== 0;
    for (var n = 0; n < L; n++) { cnp[n + 1] <== cnp[n] + cIp[n] * cIp[n]; }
    signal pi2 <== ipI[L] * ipI[L];
    signal penv2 <== pi2 + ipQ[L] * ipQ[L];
    signal pC <== EP[L] * cnp[L];
    component rp = Range(96);
    rp.in <== B * penv2 - pC;
    component w0 = Num2Bits(33); w0.in <== aPartner - pPartner + WPRE;
    component w1 = Num2Bits(33); w1.in <== pPartner + WPOST - aPartner;

    // ================= (6) half and its commitment
    signal half <== (1 - 2 * roleB) * (aPartner - aSelf);
    component hcm = Sponge16(6, 4);
    hcm.in[0] <== nonceHi; hcm.in[1] <== nonceLo; hcm.in[2] <== attempt; hcm.in[3] <== roleB;
    hcm.in[4] <== half; hcm.in[5] <== salt;
    halfCommit <== hcm.o1;
}

component main {public [nonceHi, nonceLo, attempt, roleB, codeHi, codeLo, cIs, cQs, cIp, cQp, recRoot, pSelf, pPartner]} = OA2();
