pragma circom 2.2.3;
// generated by gen_circuit.py: delta=48 (1 ms) K=97 NS=12158 NLS=13 NP=12062 NLP=13
// window=w400 [-7200, +12000] L=12000 M=63 HM=31 B=4474747 W=96 sig=True
include "oa2lib.circom";
include "sb.circom";

template OA2() {
    var L = 12000;
    var K = 97;
    var DELTA = 48;
    var HM = 31;
    var M = 63;
    var NS = 12158;
    var NP = 12062;
    var NLS = 13;
    var NLP = 13;
    var WPRE = 7200;
    var WPOST = 12000;
    var B = 4474747;
    var h[M] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 4, -1, 0, 2, -7, 0, -5, -13, 0, -19, -13, 0, -45, 27, 127, 27, -45, 0, -13, -19, 0, -13, -5, 0, -7, 2, 0, -1, 4, 0, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0];

    // ---------------- public
    signal input nonceHi;
    signal input nonceLo;
    signal input attempt;
    signal input roleB;
    signal input codeHi;          // code_commit (SHA-256 of the int8 templates) as 2 x 128-bit limbs
    signal input codeLo;
    signal input cIs[L];          // own template (self arrival), 8-bit; verifier derives it
    signal input cQs[L];
    signal input cIp[L];          // partner template
    signal input cQp[L];
    signal output halfCommit;
    signal input issuerX;
    signal input issuerY;
    signal input sr;
    signal input validAt;
    signal output nullifier;
    signal output pairTag;
    // ---------------- private: signed transcript fields, signatures, credential
    signal input ownPub[64];
    signal input partnerPub[64];
    signal input halfBytes[4];
    signal input recBytes[32];
    signal input pSelfB[4];
    signal input pPartnerB[4];
    signal input deltaB[2];
    signal input aSelfB[4];
    signal input aPartnerB[4];
    signal input ts[8];
    signal input sig_r;
    signal input sig_sInv;
    signal input exp[8];
    signal input cred_r;
    signal input cred_sInv;
    signal input holderSecret;
    signal input holdCommit[32];
    signal input salt;
    // ---------------- private: recording openings, claimed curve, arrival selector
    signal input xs[NLS][1024];
    signal input chS[NLS][6][4];
    signal input leafS;
    signal input xp[NLP][1024];
    signal input chP[NLP][6][4];
    signal input leafP;
    signal input I[K];
    signal input Q[K];
    signal input u[K];            // u[j] = [j < a_self - (p_self - delta)]

    // ================= (1) transcript, signature, credential
    component hdr = PublicHeader();
    hdr.nonceHi <== nonceHi;
    hdr.nonceLo <== nonceLo;
    hdr.attempt <== attempt;
    hdr.sr <== sr;
    hdr.validAt <== validAt;
    roleB * (roleB - 1) === 0;
    component bO = BytesBits(64); bO.in <== ownPub;
    component bP = BytesBits(64); bP.in <== partnerPub;
    component bH = BytesBits(4); bH.in <== halfBytes;
    component bR = BytesBits(32); bR.in <== recBytes;
    component bPS = BytesBits(4); bPS.in <== pSelfB;
    component bPP = BytesBits(4); bPP.in <== pPartnerB;
    component bD = BytesBits(2); bD.in <== deltaB;
    component bAS = BytesBits(4); bAS.in <== aSelfB;
    component bAP = BytesBits(4); bAP.in <== aPartnerB;
    component bT = BytesBits(8); bT.in <== ts;
    component cH = NumBitsBE(128); cH.in <== codeHi;
    component cL = NumBitsBE(128); cL.in <== codeLo;
    component sha = Sha256(8 * 265);
    var k = 0;
    var magic[4] = [0x53, 0x42, 0x76, 0x32];   // "SBv2"
    for (var i = 0; i < 4; i++) { for (var j = 0; j < 8; j++) { sha.in[k] <== (magic[i] >> (7 - j)) & 1; k++; } }
    for (var i = 0; i < 256; i++) { sha.in[k] <== hdr.nonceBits[i]; k++; }
    for (var i = 0; i < 8; i++) { sha.in[k] <== hdr.attemptBits[i]; k++; }
    for (var j = 0; j < 6; j++) { sha.in[k] <== (0x41 >> (7 - j)) & 1; k++; }
    sha.in[k] <== roleB; k++;
    sha.in[k] <== 1 - roleB; k++;
    for (var i = 0; i < 512; i++) { sha.in[k] <== bO.out[i]; k++; }
    for (var i = 0; i < 512; i++) { sha.in[k] <== bP.out[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== hdr.srBits[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== bH.out[i]; k++; }
    for (var i = 0; i < 256; i++) { sha.in[k] <== bR.out[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== bPS.out[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== bPP.out[i]; k++; }
    for (var i = 0; i < 16; i++) { sha.in[k] <== bD.out[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== bAS.out[i]; k++; }
    for (var i = 0; i < 32; i++) { sha.in[k] <== bAP.out[i]; k++; }
    for (var i = 0; i < 128; i++) { sha.in[k] <== cH.out[i]; k++; }
    for (var i = 0; i < 128; i++) { sha.in[k] <== cL.out[i]; k++; }
    for (var j = 0; j < 8; j++) { sha.in[k] <== (1 >> (7 - j)) & 1; k++; }
    for (var i = 0; i < 64; i++) { sha.in[k] <== bT.out[i]; k++; }

    component xO = PackBytes(32); component yO = PackBytes(32); component xP = PackBytes(32);
    for (var i = 0; i < 32; i++) { xO.in[i] <== ownPub[i]; yO.in[i] <== ownPub[32 + i]; xP.in[i] <== partnerPub[i]; }
    component dsig = VerifyDigestSig();
    dsig.digest <== sha.out;
    dsig.r <== sig_r;
    dsig.sInv <== sig_sInv;
    dsig.pubX <== xO.out;
    dsig.pubY <== yO.out;

    // credential SBcred3 = "SBcred3" | pub | expiry | holder_commit, signed by the issuer
    component bE = BytesBits(8); bE.in <== exp;
    component bC = BytesBits(32); bC.in <== holdCommit;
    component csha = Sha256(8 * 111);
    var kc = 0;
    var cmag[7] = [0x53, 0x42, 0x63, 0x72, 0x65, 0x64, 0x33];
    for (var i = 0; i < 7; i++) { for (var j = 0; j < 8; j++) { csha.in[kc] <== (cmag[i] >> (7 - j)) & 1; kc++; } }
    for (var i = 0; i < 512; i++) { csha.in[kc] <== bO.out[i]; kc++; }
    for (var i = 0; i < 64; i++) { csha.in[kc] <== bE.out[i]; kc++; }
    for (var i = 0; i < 256; i++) { csha.in[kc] <== bC.out[i]; kc++; }
    component isig = VerifyDigestSig();
    isig.digest <== csha.out;
    isig.r <== cred_r;
    isig.sInv <== cred_sInv;
    isig.pubX <== issuerX;
    isig.pubY <== issuerY;
    component expV = PackBytes(8); expV.in <== exp;
    component notExpired = LessEqThan(64);
    notExpired.in[0] <== validAt;
    notExpired.in[1] <== expV.out;
    notExpired.out === 1;

    // holder secret bound to the credential; nullifier; own != partner; pair tag
    component hc = Sponge16(1, 6); hc.in[0] <== holderSecret;
    component hcv = PackBytes(32); hcv.in <== holdCommit;
    hcv.out === hc.o1;
    component nf = Sponge16(3, 5);
    nf.in[0] <== holderSecret; nf.in[1] <== nonceHi; nf.in[2] <== nonceLo;
    nullifier <== nf.o1;
    component same = IsEqual(); same.in[0] <== xO.out; same.in[1] <== xP.out; same.out === 0;
    signal xA <== xO.out + roleB * (xP.out - xO.out);
    signal xB <== xP.out + roleB * (xO.out - xP.out);
    component pt = Sponge16(4, 7);
    pt.in[0] <== nonceHi; pt.in[1] <== nonceLo; pt.in[2] <== xA; pt.in[3] <== xB;
    pairTag <== pt.o1;

    // transcript values
    component vR = PackBytes(32); vR.in <== recBytes;
    component vPS = PackBytes(4); vPS.in <== pSelfB;
    component vPP = PackBytes(4); vPP.in <== pPartnerB;
    component vD = PackBytes(2); vD.in <== deltaB;
    component vAS = PackBytes(4); vAS.in <== aSelfB;
    component vAP = PackBytes(4); vAP.in <== aPartnerB;
    component vH = SignedI32(); vH.bits <== bH.out;
    vD.out === DELTA;
    signal recRoot <== vR.out;
    signal pSelf <== vPS.out;
    signal pPartner <== vPP.out;
    signal aSelf <== vAS.out;
    signal aPartner <== vAP.out;

    // ================= (2) open the recording: self and partner regions
    // self region starts at the leaf holding p_self - delta - HM; oS = offset inside that leaf
    signal oS <== pSelf - DELTA - HM - 1024 * leafS;
    component oSb = Num2Bits(10); oSb.in <== oS;
    component opS = OpenLeaves(NLS);
    opS.x <== xs; opS.first <== leafS; opS.ch <== chS; opS.root <== recRoot;
    signal oP <== aPartner - HM - 1024 * leafP;
    component oPb = Num2Bits(10); oPb.in <== oP;
    component opP = OpenLeaves(NLP);
    opP.x <== xp; opP.first <== leafP; opP.ch <== chP; opP.root <== recRoot;
    // shift to the window start (barrel shifter over the 10 offset bits)
    component shS = Barrel1024(NLS * 1024, NS);
    for (var i = 0; i < NLS; i++) { for (var j = 0; j < 1024; j++) { shS.in[1024 * i + j] <== xs[i][j]; } }
    shS.bits <== oSb.out;
    component shP = Barrel1024(NLP * 1024, NP);
    for (var i = 0; i < NLP; i++) { for (var j = 0; j < 1024; j++) { shP.in[1024 * i + j] <== xp[i][j]; } }
    shP.bits <== oPb.out;
    // shS.out[i] = x[p_self - delta - HM + i];  shP.out[i] = x[a_partner - HM + i]

    // ================= (3) Fiat-Shamir challenge over everything committed, Freivalds on the self curve
    component fs = Sponge16(206, 52739);
    fs.in[0] <== nonceHi; fs.in[1] <== nonceLo; fs.in[2] <== attempt; fs.in[3] <== roleB;
    fs.in[4] <== recRoot; fs.in[5] <== pSelf; fs.in[6] <== pPartner; fs.in[7] <== DELTA;
    fs.in[8] <== aSelf; fs.in[9] <== aPartner; fs.in[10] <== codeHi; fs.in[11] <== codeLo;
    for (var j = 0; j < K; j++) { fs.in[12 + j] <== I[j]; fs.in[12 + K + j] <== Q[j]; }
    signal r <== fs.o1;
    signal rho <== fs.o2;
    var N = K + L - 1;
    signal pw[N];
    pw[0] <== 1;
    for (var i = 1; i < N; i++) { pw[i] <== pw[i - 1] * r; }
    signal S[N + 1];
    S[0] <== 0;
    for (var m = 1; m <= N; m++) { S[m] <== S[m - 1] + pw[m - 1] * shS.out[HM + m - 1]; }
    signal v[L];
    signal uu[L];
    signal acc[L + 1];
    acc[0] <== 0;
    for (var n = 0; n < L; n++) {
        v[n] <== rho * cQs[n];
        uu[n] <== (cIs[n] + v[n]) * pw[L - 1 - n];
        acc[n + 1] <== acc[n] + uu[n] * (S[n + K] - S[n]);
    }
    signal li[K + 1];
    signal lq[K + 1];
    li[0] <== 0;
    lq[0] <== 0;
    for (var j = 0; j < K; j++) {
        li[j + 1] <== li[j] + pw[j] * I[j];
        lq[j + 1] <== lq[j] + pw[j] * Q[j];
    }
    signal lhs <== li[K] + rho * lq[K];
    signal lhs2 <== pw[L - 1] * lhs;
    lhs2 === acc[L];

    // ================= normalization (self): E_j = sum_(m<L) y[j+m]^2, y = FIR(x); cn2 = |cI|^2
    signal EY[N + 1];
    EY[0] <== 0;
    for (var m = 0; m < N; m++) {
        var yl = 0;
        for (var t = 0; t < M; t++) { if (h[t] != 0) { yl += h[t] * shS.out[m + t]; } }
        EY[m + 1] <== EY[m] + yl * yl;
    }
    signal cna[L + 1];
    cna[0] <== 0;
    for (var n = 0; n < L; n++) { cna[n + 1] <== cna[n] + cIs[n] * cIs[n]; }

    // ================= (4) self arrival: first lag >= bar in [p_self - delta, p_self + delta]
    u[K - 1] === 0;
    var usum = 0;
    for (var j = 0; j < K; j++) {
        u[j] * (u[j] - 1) === 0;
        if (j > 0) { u[j] * (1 - u[j - 1]) === 0; }
        usum += u[j];
    }
    usum === aSelf - pSelf + DELTA;         // => a_self in [p_self - delta, p_self + delta]
    signal C[K];
    signal i2[K];
    signal env2[K];
    signal pu[K];
    signal pe[K];
    component rk[K];
    for (var j = 0; j < K; j++) {
        C[j] <== (EY[j + L] - EY[j]) * cna[L];
        i2[j] <== I[j] * I[j];
        env2[j] <== i2[j] + Q[j] * Q[j];
        var D = C[j] - B * env2[j];         // D > 0  <=>  score < bar
        var e = (j == 0 ? 1 : u[j - 1]) - u[j];   // one-hot at the arrival
        pu[j] <== u[j] * (D - 1);            // before the arrival: D - 1 >= 0
        pe[j] <== e * D;                     // at the arrival: -D >= 0
        rk[j] = Range(96);
        rk[j].in <== pu[j] - pe[j];
    }

    // ================= (5) partner arrival: one lag, score >= bar, inside the pinned window
    signal ipI[L + 1];
    signal ipQ[L + 1];
    ipI[0] <== 0;
    ipQ[0] <== 0;
    for (var n = 0; n < L; n++) {
        ipI[n + 1] <== ipI[n] + cIp[n] * shP.out[HM + n];
        ipQ[n + 1] <== ipQ[n] + cQp[n] * shP.out[HM + n];
    }
    signal EP[L + 1];
    EP[0] <== 0;
    for (var m = 0; m < L; m++) {
        var yl = 0;
        for (var t = 0; t < M; t++) { if (h[t] != 0) { yl += h[t] * shP.out[m + t]; } }
        EP[m + 1] <== EP[m] + yl * yl;
    }
    signal cnp[L + 1];
    cnp[0] <== 0;
    for (var n = 0; n < L; n++) { cnp[n + 1] <== cnp[n] + cIp[n] * cIp[n]; }
    signal pi2 <== ipI[L] * ipI[L];
    signal penv2 <== pi2 + ipQ[L] * ipQ[L];
    signal pC <== EP[L] * cnp[L];
    component rp = Range(96);
    rp.in <== B * penv2 - pC;
    component w0 = Num2Bits(33); w0.in <== aPartner - pPartner + WPRE;
    component w1 = Num2Bits(33); w1.in <== pPartner + WPOST - aPartner;

    // ================= (6) half and its commitment
    signal half <== (1 - 2 * roleB) * (aPartner - aSelf);
    vH.out === half;
    component hcm = Sponge16(6, 4);
    hcm.in[0] <== nonceHi; hcm.in[1] <== nonceLo; hcm.in[2] <== attempt; hcm.in[3] <== roleB;
    hcm.in[4] <== half; hcm.in[5] <== salt;
    halfCommit <== hcm.o1;
}

component main {public [nonceHi, nonceLo, attempt, roleB, codeHi, codeLo, cIs, cQs, cIp, cQp, issuerX, issuerY, sr, validAt]} = OA2();
