pragma circom 2.2.3;
// generated by gen_popt2.py: pair statement over two POPT v2 per-phone half commitments, per-phone sample rates.
include "oa2tlib.circom";

template Pair2() {
    signal input nonceHi;
    signal input nonceLo;
    signal input attempt;
    signal input commitA;
    signal input commitB;
    signal input srA;
    signal input srB;
    signal input halfA;
    signal input saltA;
    signal input halfB;
    signal input saltB;
    signal input xA;          // X of device A's key (A's own, B's partner)
    signal input xB;
    component ca = Sponge16(9, 8);
    ca.in[0] <== nonceHi; ca.in[1] <== nonceLo; ca.in[2] <== attempt; ca.in[3] <== 0;
    ca.in[4] <== srA; ca.in[5] <== halfA; ca.in[6] <== saltA; ca.in[7] <== xA; ca.in[8] <== xB;
    ca.o1 === commitA;
    component cb = Sponge16(9, 8);
    cb.in[0] <== nonceHi; cb.in[1] <== nonceLo; cb.in[2] <== attempt; cb.in[3] <== 1;
    cb.in[4] <== srB; cb.in[5] <== halfB; cb.in[6] <== saltB; cb.in[7] <== xB; cb.in[8] <== xA;
    cb.o1 === commitB;
    component same = IsEqual(); same.in[0] <== xA; same.in[1] <== xB; same.out === 0;
    // i32 halves, rates in [SR_MIN, SR_MAX]
    component ra = Num2Bits(32); ra.in <== halfA + (1 << 31);
    component rb = Num2Bits(32); rb.in <== halfB + (1 << 31);
    component sa0 = Num2Bits(17); sa0.in <== srA - 36000;
    component sa1 = Num2Bits(17); sa1.in <== 96000 - srA;
    component sb0 = Num2Bits(17); sb0.in <== srB - 36000;
    component sb1 = Num2Bits(17); sb1.in <== 96000 - srB;
    // NEAR iff -20 < c/2 (hA/srA - hB/srB) < 60, c = 34300 cm/s, times 2 srA srB > 0.
    // |c N| < 34300 * 2^31 * 2^17 * 2 < 2^65 and 2 NEAR S < 2^41, so (value - 1) in 70 bits <=> value >= 1.
    signal t1 <== halfA * srB;
    signal t2 <== halfB * srA;
    signal S <== srA * srB;
    signal N <== t1 - t2;
    component gtLo = Num2Bits(70); gtLo.in <== 34300 * N + 40 * S - 1;
    component ltHi = Num2Bits(70); ltHi.in <== 120 * S - 34300 * N - 1;
}

component main {public [nonceHi, nonceLo, attempt, commitA, commitB, srA, srB]} = Pair2();
